### ISSUE TITLE
Unable to add as collaborator

### ISSUE THREAD

**Issue by ratairas** [education/classroom#1271] opened 2018-02-15 21:01 UTC
One of my students is unable to create a repository. The error message "We were not able to add you to the assignment as a collaborator on this assignment. Please try again." came up. Other students have been able to accept the assignment, the latest as being about three hours ago. When I go to the organization dashboard, it shows the repository being generated several times, but it does not show up on the list (main page of organization).

**Comment by matt297** [comment] 2018-02-15 22:45
My students are encountering the same issue when they try and accept an assignment invitation -
 they always get the error message, `We were not able to add you to the assignment as a collaborator on this assignment. Please try again.`

I tried creating a brand new assignment (https://classroom.github.com/a/8FyDefF3), but accepting the invitation produces the same error. One student tried revoking their GitHub Classroom OAuth token, authorizing GitHub Classroom again, and then trying the assignment invitation, but still received the same error.

When I (the organization admin as well as the person who created the assignment starter repo) try and accept the invitation, it works without a problem.

**Comment by rmquimby** [comment] 2018-02-15 23:30
My students are suddenly having this same problem. All students were able to access assignments yesterday, but as of a few hours ago none of them can.

**Comment by filalano** [comment] 2018-02-15 23:55
I have the same issue at the moment! https://classroom.github.com/a/UvQiVcNw

**Comment by Kadaaran** [comment] 2018-02-16 15:21
Hello everyone,

Thank you for reporting this issue.

@ratairas @rmquimby can you give me your organization ID and the assignment so we can take a look at it ?
@filalano @matt297 Can you give me the name of the assignment you're talking about so we can take a look ?

**Comment by ratairas** [comment] 2018-02-16 15:38
@Kadaaran My organization ID is vu-cs3270-s18 and assignment is Project 1. I tried Homework 3 and it didn't work either.

Thanks.

**Comment by Kadaaran** [comment] 2018-02-16 15:44
@ratairas Do you have the login or name of a student that got the repository created multliple times and on which assignment ?

**Comment by ratairas** [comment] 2018-02-16 15:46
@Kadaaran Here's one: vandercc gets an error on Homework 3 and Project 1.

**Comment by ghemingway** [comment] 2018-02-16 15:48
@Kadaaran I am seeing this issue also.  My organization is vu-cs3251-s18 assignment is Assignment 3.  The student with the issue's GH account ID is: kzhang798.

**Comment by matt297** [comment] 2018-02-16 16:43
@Kadaaran The organization id is `34665183` and the assignment name is `Test Assignment` (https://classroom.github.com/a/8FyDefF3). All of my students are getting the error, but if it helps, a couple specifically are `navroop9152` and `chaoxunzhou`.

**Comment by laleese** [comment] 2018-02-16 17:33
@Kadaaran - our org is @CS-112-02-spring2018 and its for Lab3
URL: https://classroom.github.com/a/UvQiVcNw

**Comment by mmm** [comment] 2018-02-16 17:39
We're seeing the same thing for multiple classrooms.

The audit log for the org shows lots of: `repo.create`, `repo.add_member`, and then `repo.destroy` events for the problematic student assignment repos, but doesn't include any error messages

**Comment by rmquimby** [comment] 2018-02-16 17:40
Thanks @Kadaaran . My organization id is 35276586. The problem first showed up with my assignment `homework#4` (some students successfully accepted, but later others could not). None of my students were able to  accept `Quiz #6`.

**Comment by FanBu** [comment] 2018-02-16 19:18
It seems like something is wrong here. https://github.com/education/classroom/blob/6a50c7febf555fb1ba91c79b0b9f0062134dde0e/app/models/github_organization.rb#L29
The repo cannot be created but the user is invited to the repo.

**Comment by tarebyte** [comment] 2018-02-16 19:23
Hi Everyone,

First thank you for reporting this issue, we really appreciate the community bringing these problems to us.

There was a deploy that made a breaking change to the GitHub API yesterday afternoon which is what is causing your issues.

I'm currently working on a PR to fix the API problem and then a subsequent PR to fix this issue on the Classroom side.

Thank you for your patience.

**Comment by FanBu** [comment] 2018-02-16 19:30
The error is raised here https://github.com/education/classroom/blob/6a50c7febf555fb1ba91c79b0b9f0062134dde0e/app/models/assignment_repo/creator.rb#L106
because the controller tries to add users to a repo which is failed during creation.
However, I think the error should be raised within https://github.com/education/classroom/blob/6a50c7febf555fb1ba91c79b0b9f0062134dde0e/app/models/assignment_repo/creator.rb#L113

**Comment by DbCrWk** [comment] 2018-02-16 21:40
I'm also having this issue. Commenting here to stay subscribed!

**Comment by Percipient24** [comment] 2018-02-16 22:18
I'm also having this issue. I'm happy to provide additional details / add you to my ORG / act as test subject.

**Comment by whatwho** [comment] 2018-02-17 11:39
Our students are having the same issue, commenting here just to stay subscibed! Thanks for the quick fix in advance!

**Comment by malloc82** [comment] 2018-02-17 22:59
One of my students had the same issue, but I was able to fix it by converting him to "outside collaborator" from "member" manually. 

He was listed as a organization member because github classroom added first time students as member last fall. However, this semester github added first time students as an "outside collaborator". 

So all the students who listed as "outside collaborator" had no problem accepting assignment, the only student who listed as member had that issue, and I was able to fix it by converting him to "outside collaborator".

**Comment by sebkopf** [comment] 2018-02-18 05:28
Same problem with our students, could not solve it with malloc82's suggestion. Thanks in advance for working on the fix.

**Comment by malloc82** [comment] 2018-02-18 05:36
Just want to add that at the moment, not even organization's owner can accept assignment, only "outside collaborator" can accept assignment in my classroom. 

And my assignments are all individual assignments.

**Comment by DbCrWk** [comment] 2018-02-18 09:15
@malloc82 I'm experiencing similar behavior

**Comment by coatless** [comment] 2018-02-18 20:29
@Kadaaran thanks for your work on the problem thus far. However, is there an ETA expected for this fix or should I start working on a side script to spin up repos for students?

**Comment by Percipient24** [comment] 2018-02-19 05:33
I'm writing to confirm @malloc82's 'outside collaborator' fix worked for me and my students. Go to https://github.com/orgs/[your org here]/people and, for each student, select 'Convert to outside collaborator' from the settings cog menu:

<img width="282" alt="screen shot 2018-02-19 at 12 30 44 am" src="https://user-images.githubusercontent.com/1882129/36363601-663e1cb6-150c-11e8-86d2-1f5a345b606d.png">

Thanks @malloc82 !

**Comment by arjenpdevries** [comment] 2018-02-19 09:09
Worked here as well, tnx @malloc82

**Comment by arjenpdevries** [comment] 2018-02-19 09:13
Is there an ETA for a solution, @tarebyte ?

(I need to hand out new assignments on Thursday, would be nice to know if I need to look for a workaround or that this will likely not be an issue anymore.)

**Comment by AlexHartveld** [comment] 2018-02-19 16:27
We're having the same issues, commenting here to keep updated about a possible fix. 
Thanks for going after this, hope the PR is done soon.

**Comment by lubaochuan** [comment] 2018-02-19 16:39
I am experiencing the same issue. Couldn't accept this assignment created by myself: https://classroom.github.com/a/ajnTka1E

**Comment by malloc82** [comment] 2018-02-19 16:47
@lubaochuan I just accepted your assignment. I don't know if you are a owner or member, but at the moment, only "outside collaborator" or people have no association to the organization (like me) at all can accept the repo.

**Comment by kmmcgarry** [comment] 2018-02-19 16:52
I'm having the same issue. Patiently waiting for an update on this.

**Comment by vuse-student** [comment] 2018-02-19 18:54
@ratairas @ghemingway pls daddy

**Comment by maryvilleDevProf** [comment] 2018-02-19 20:35
Adding myself to the listener list. Thanks for working on this!

**Comment by mrmirah** [comment] 2018-02-20 15:11
Thank you for the workaround for now and working quickly to get a fix.  Subscribing to this to stay updated.

**Comment by kraigh** [comment] 2018-02-20 19:02
Would like to chime in that we're experiencing a similar issue- students are able to clone the repos, but the "Give students Admin permissions on their repository" option is not honored, and students are not added as administrators on their repository, only write permissions. This is an issue for us because students use Github Pages to host their site, and they cannot set up Github Pages without admin access.

**Comment by lubaochuan** [comment] 2018-02-22 13:40
@malloc82 Thanks for your comment. It turned out a few of my students were considered inside collaborators because they were added to a team in my organization last year. The issue is definitely new because none of my students had issues accepting assignments just a few weeks ago. It seems the issue has been fixed.

**Comment by Kadaaran** [comment] 2018-02-28 21:12
Hi everyone, 

You can find the report of the last week's incident [here](https://education.github.community/t/en-fr-github-classroom-incident-report-28-february-2018-rapport-dincident-28-fevrier-2018/26616) if you want more informations about what happened and how it was resolved.

Thank you ✨

**Comment by rossdakin** [comment] 2018-03-04 23:44
@Kadaaran was this intentionally reopened? Are there ongoing/new issues?

Thanks!

**Comment by Kadaaran** [comment] 2018-03-05 09:48
Hi @rossdakin , we are keeping it open in case some people still experience this issue. 
If there is no issues related to this one we will close it in a few weeks :)

**Closed** 2018-03-19 13:28 UTC
Labels: :bookmark_tabs: assignments, :bug: bug

**Comment by fvanwijk** [comment] 2018-06-12 13:37
It looks like the student needs 2FA enabled if the owning organisation required 2FA for alle collaborators

**Comment by ericpollmann** [comment] 2019-02-05 22:23
I'm experiencing this issue again, we do not have 2FA on, and 2 of 8 students who attempted to accept the assignment failed setup with this message.

**Comment by jbschrades** [comment] 2019-05-14 16:23
We are seeing this issue with some (not all) of our students.  We do not have 2FA enabled at the org level.

**Comment by mehraUTD** [comment] 2020-01-29 05:59
I am having the same issue! any updates?

**Comment by d12** [comment] 2020-01-29 14:45
@mehraUTD We're working on solving this issue with template repo imports, which should reduce the error rate here. More info: https://classroom.github.com/help/using-template-repos-for-assignments
