### ISSUE TITLE
"Cannot retrieve this organizations repo plan, please reauthenticate your token."

### ISSUE THREAD

**Issue by potash** [education/classroom#1340] opened 2018-04-05 17:07 UTC
#### What you were trying to do ?
My students are trying to accept an assignment

#### What happened (include screenshot if you can) ?
They get the error "cannot retrieve this organizations repo plan, please reauthenticate your token."

#### Step-by-step reproduction instructions
Visit accept assignment link (e.g. https://classroom.github.com/a/ea-FaLox)

Sometimes it is fixed if a student logs out of github classroom and logs back in. Note that the error does not always happen and even sometimes when it happens the student assignment repo still gets created.

**Comment by Kadaaran** [comment] 2018-04-06 15:31
Hi @potash , your issues is a duplicate of #664 , I invite you to go there to be updated about it.

Just to let you know, this issue appears when an owner has been removed from your organization in GitHub but not in Classroom but we recently merged a fix to this issue 👍 

I invite you to check if the owners of your organization are the same than your administrators in GitHub Classroom.
If it's not the case, you can revoke their Classroom access in your settings in Classroom.
This should resolve your issue quickly.

Thank you for your patience 🙏

**Closed by Kadaaran** 2018-04-06 15:31 UTC
