### ISSUE TITLE
Cannot import starter code

### ISSUE THREAD

**Issue by QianYuTanzanite** [education/classroom#1781] opened 2019-02-25 02:40 UTC
**Describe the bug**
After accepting the assignment I cannot import the starter code and it just never finishes

**To Reproduce**
1. Go to https://classroom.github.com/a/k6Js2LWc
2. Click on Accept assignment
3. See error

**Expected behavior**
The assignment should be accepted and a repo link should pop up

**Screenshots**
![capture](https://user-images.githubusercontent.com/46547652/53310914-c133ac00-387c-11e9-9471-493da9e3b494.PNG)

**Comment by BenEmdon** [comment] 2019-02-25 03:19
Duplicate of #1778

**Comment by BenEmdon** [comment] 2019-02-25 04:23
I can confirm that starter code imports are working again on your classroom. 

Your import may take a couple of hours to complete but it will complete eventually. This issue is due to a minor outage on GitHub.com. See #1778 for details.

If you continue to experience this problem after a couple of hours please report back.

**Closed by BenEmdon** 2019-02-25 04:23 UTC
Labels: duplicate
