### ISSUE TITLE
 The members in my organization cant enter the github classroom page

### ISSUE THREAD

**Issue by zsw12abc** [education/classroom#266] opened 2015-09-24 01:54 UTC
i just invite them into my organization
after they accepted, they cant enter the classroom page.

**Comment by tarebyte** [comment] 2015-09-24 02:04
@zsw12abc only owners of the organization can see your pages on Classroom for GitHub that aren't invitation pages.

**Comment by zsw12abc** [comment] 2015-09-24 02:07
so if i want to give them assignment, the only thing i can do is give them the link of the assignment?

**Comment by zsw12abc** [comment] 2015-09-24 02:09
and when they accept this assignment, they get the error message:
You are forbidden from performing this action on github.com

**Comment by tarebyte** [comment] 2015-09-24 02:11
can you give me the assignment link to try out?

**Comment by zsw12abc** [comment] 2015-09-24 02:12
yes 
here is the link
https://classroom.github.com/assignment-invitations/b6680a4cd50797ad1155bde741d20c79

**Comment by zsw12abc** [comment] 2015-09-24 02:16
i just create another account for testing it.
what i do is i invite the test account into my organization
then, i use the test account to click this link and try to accept the assignment.
it gives me the error message, You are forbidden from performing this action on github.com
then, i find that there is a secret team automatically created and the name is same as the test account's name, but test account is not in this team.
so i just add my test account into this team.
then, test account try to accept assignment again, now error massage changes to
Team already exists name

**Comment by johndbritton** [comment] 2015-09-24 11:06
I am also seeing this issue @tarebyte.

**Comment by tarebyte** [comment] 2015-09-24 11:45
@zsw12abc I'm pretty sure I'm right, but is your organization in question a new beta GitHub org?

**Comment by geeeeeeeeek** [comment] 2015-09-29 12:37
same issue here
https://classroom.github.com/assignment-invitations/4d93730a57a97790ac76df9c71ab1fd9

**Comment by johndbritton** [comment] 2015-09-29 12:45
This issue is caused by changes [introduced](https://github.com/blog/2020-improved-organization-permissions) with [improved organization permissions](https://help.github.com/articles/about-improved-organization-permissions-early-access-program/).

**Comment by geeeeeeeeek** [comment] 2015-10-04 17:54
@johndbritton I wanna know when will this bug be fixed? Since our first code assignment comes in days...

**Comment by johndbritton** [comment] 2015-10-05 09:37
@geeeeeeeeek I can't promise when it will be fixed, but we are working on a resolution.

**Comment by johndbritton** [comment] 2015-10-12 11:22
@tarebyte and I have been investigating this and I think the improved organization permissions aspect of this is unrelated to the actual problem.

It looks like we're getting a `UnprocessableEntity` error. Perhaps there are some character encoding issues with the assignment title.

**Comment by geeeeeeeeek** [comment] 2015-10-12 12:58
My original starter repo contains Chinese, which may cause encoding issues. Now I changed the repo name to pure English and it works all right. But I still think this issue should be handled seriously.

**Comment by johndbritton** [comment] 2015-10-12 14:42
> My original starter repo contains Chinese

That was my suspicion, but I couldn't figure out where the characters were coming from. What was the original name of your starter code repository?

> But I still think this issue should be handled seriously.

Definitely.

**Comment by geeeeeeeeek** [comment] 2015-10-12 14:53
If I remember correctly, the starter repo is [WeChatLuckyMoney](https://github.com/geeeeeeeeek/WeChatLuckyMoney). The name has no Chinese itself, but I created an assignment called "Service实例：微信抢红包实例". That includes a fullwidth colon and Chinese characters. I don't know if it was the one causing the issue.

**Comment by johndbritton** [comment] 2015-10-12 15:10
I was able to successfully join your class using the invitation link, but it took two tries.

Are you currently having problems that are blocking you from using the application or have you found a suitable workaround?

We're still going to work on a fix for the original problem, but I want to make sure you're able to continue.

**Comment by geeeeeeeeek** [comment] 2015-10-12 17:18
Thanks for all of your work. It seems okay to join the assignments now. But considering the need for private repos, we are now using GitLab as a substitute. Classroom is a great project. Glad to see it being better!

**Comment by johndbritton** [comment] 2015-10-12 17:38
> But considering the need for private repos

As a teacher you can get free private repositories in your organization at https://education.github.com/discount

**Comment by floe** [comment] 2015-10-23 11:44
I seem to have a similar issue, perhaps caused by German umlaut characters ("Übung 2") for the mmbuw org. I removed the assignments for now and switched to "plain" Github for the class.

**Comment by tarebyte** [comment] 2016-09-07 01:32
Fixed in #728

**Closed by tarebyte** 2016-09-07 01:32 UTC
Labels: bug
