### ISSUE TITLE
Process of 'Importing starter pack' is stuck

### ISSUE THREAD

**Issue by swaaz** [education/classroom#1765] opened 2019-02-14 07:51 UTC
**Describe the bug**
whenever you accept the assignment, it opens the page and displays the message "Your assignment repository is being setup. This might take a while." and the progress bar will be shown down. And the process of creating repository will be completed but the process of importing starter code will not complete.I  waited for an hour but it's not completed yet.
**To Reproduce**
1. Go to 'https://classroom.github.com/assignment-invitations/98375f0d9630f6100ecb396612c98cfd/setup'

**Expected behavior**
I expected the progress to be completed and can start my assignment.

**Screenshots**
![image](https://user-images.githubusercontent.com/42874695/52770819-222bda80-305a-11e9-830c-b6e920b6ffa4.png)

**Additional context**

**Comment by eblanton** [comment] 2019-02-16 18:06
This was reported two weeks ago in #1757, with no comment or acknowledgment from the GHC team.  I am still having this problem running my class, and GHC has become basically unusable.  I'm not sure any students have been able to successfully clone in days.

Your instructor should be able to fix this manually, I wouldn't hold out hope for a GHC fix.

**Comment by swaaz** [comment] 2019-02-17 08:57
How to fix this issue? Do we have any other way? I'm an instructor and how should I fix?

**Comment by eblanton** [comment] 2019-02-17 14:13
I have been fixing student accounts with the following technique (assuming that the student GH account is $STUDENT, the GHC organization is in $ORG, and the project repo prefix is $PREFIX):

 * Check out the master repository on the local machine, and cd to that directory.
 * On the GitHub web site, create a student repository $ORG/$PREFIX-$STUDENT
 * Add $STUDENT to the new repository as a collaborator under Settings, Collaborators & Teams
 * run `git push git@github.com:$ORG/$PREFIX-$STUDENT` from the local master repository
 * Let the student know you're done

This can be largely automated using the GitHub APIs and some simple scripting, which is my plan for future projects, since GHC appears to be far more work than it's worth until this is fixed.

**Comment by swaaz** [comment] 2019-02-17 15:02
Thanks buddy

**Comment by klancasterprof** [comment] 2019-02-17 16:13
@eblanton I was able to get a GHC team member to respond by tagging them in a comment, but from what I see so far they pay little or no attention to these issues. I had planned on recommending GHC to other faculty but at this point I see no reason to.

**Comment by eblanton** [comment] 2019-02-17 21:54
Yes, we are absolutely moving away from GHC (and GitHub) after this semester unless things improve rapidly.  I have been in contact with Atlassian about a hosted BitBucket, and their academic licensing is quite acceptable.  We have also had a lot of stability and connectivity problems with GitHub this semester (in the past I have had GHC problems, but GH itself was not problematic, and the GHC team was actually responsive).  It seems to me that GHC is not a priority at GitHub, and that GitHub stability and usability is possibly not a priority any more, either.

I mean, we're not _paying_ for it, so there's a limited amount of complaining that's valid -- but on the other hand, we _would_ probably pay for it if we had some reason to believe it was maintained and stable.  I mean, we're willing to throw salaries and machines at the problem, which aren't free.

**Comment by BenEmdon** [comment] 2019-02-21 20:04
@swaaz I investigated your classroom and I noticed that it was missing webhooks (related #1647). This appears to be a classroom wide problem and happens sporadically on classrooms. It is a high priority for the classroom team to fix. 

We have a manual workaround on the classroom side and I went ahead and re-enabled webhooks on your classroom. If you go to your assignment invitation (https://classroom.github.com/assignment-invitations/98375f0d9630f6100ecb396612c98cfd) it should complete importing.

I have confirmed it's working as expected on your classroom so I will close this issue for now. @swaaz please reopen this issue if you experience this problem again.

---

Reading through this thread I can understand the frustration you all are going through regarding this issue. I would like to personally resolve this issue for each of your classrooms in the meantime while we work on a fix in #1647. Please open a new issue with and include an assignment invitation link.

@eblanton I see your issue and will get to it right away (https://github.com/education/classroom/issues/1757).

I'll bring your collective frustrations up with the team to talk about how we can improve on this matter. Apologies for the inconvenience.

**Closed by BenEmdon** 2019-02-21 20:04 UTC
