### ISSUE TITLE
accepting assignment gets stuck

### ISSUE THREAD

**Issue by mahdi-b** [education/classroom#1775] opened 2019-02-23 03:33 UTC
**Describe the bug**
Accepting assignment get stuck for most students

**To Reproduce**
1. Go to 'Assignment 2'
2. Click on 'accept assignment'
3. "Importing starter code" get stuck

**Additional context**
This issue was reported by a few other users but the solution to fix it is not clear. How do I fix a webhook?

**Comment by belgort-clark** [comment] 2019-02-23 04:20
I have not heard of a fix for this yet.

**Comment by BenEmdon** [comment] 2019-02-25 03:44
Duplicate of #1778 
Please look there for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:25
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:25 UTC
Labels: duplicate
