### ISSUE TITLE
Unable to access repo

### ISSUE THREAD

**Issue by git-abhishek** [education/classroom#1691] opened 2018-11-06 21:21 UTC
**Describe the bug**
I am unable to access my classroom repository:
https://github.com/ds-umass/project2-git-abhishek/import

When I click on the invitation code, I am redirected to the following page (CS-590S-project2 @ds-umass) and it gets stuck at the "Importing starter code" phase.

![capture](https://user-images.githubusercontent.com/36498066/48094328-e3c38b80-e1df-11e8-8eef-8197f65bc1cf.PNG)

**Comment by boardfish** [comment] 2018-11-07 15:39
There were [site status issues](https://status.github.com/messages) this morning. Investigation began 10 hours ago, so while this issue predates the investigation by about 8, perhaps it's involved.

**Comment by BenEmdon** [comment] 2018-11-07 15:49
> so while this issue predates the investigation by about 8, perhaps it's involved.

Possibly? I'll confirm by cross referencing time stamps.

**Comment by git-abhishek** [comment] 2018-11-07 18:46
Hi @BenEmdon, the invitation link is https://classroom.github.com/a/emsQ9I1g
Let me know if any further information is needed from my part.

**Comment by BenEmdon** [comment] 2018-11-07 21:07
This issue appears to coincide with the GitHub.com outage that happened on November 2nd https://status.github.com/messages/2018-11-2


@git-abhishek I have gone ahead and unstuck that assignment for you. Would you mind taking a look at 
https://classroom.github.com/a/emsQ9I1g and confirm you can access your repo?

We are working on a solution for issues like this in https://github.com/education/classroom/pull/1631

**Comment by git-abhishek** [comment] 2018-11-08 03:50
@BenEmdon sorry, but it is still not working. I waited for more than 3 hours after clicking the invitation link and its still stuck at "importing starter code".

**Comment by BenEmdon** [comment] 2018-11-08 15:22
I see the problem. It appears that the source import (handled on GitHub.com is still stuck in an `importing` state). I am going to notify the appropriate teams and get this fixed for you.

**Comment by BenEmdon** [comment] 2018-11-08 16:12
@git-abhishek I went ahead and deleted your assignment repository. Go to https://classroom.github.com/a/emsQ9I1g to redeem a new assignment repository.

**Comment by git-abhishek** [comment] 2018-11-08 16:23
Thank you @BenEmdon. I am now able to access the repository!

**Comment by BenEmdon** [comment] 2018-11-08 16:34
Excellent! 
Glad to hear @git-abhishek. 
Closing this issue as it was caused by the GitHub outage https://status.github.com/messages/2018-11-2.

**Closed** 2018-11-08 16:35 UTC
Labels: bug :beetle:
