### ISSUE TITLE
Code Stuck at Importing

### ISSUE THREAD

**Issue by derekShaheen** [education/classroom#2462] opened 2019-11-03 05:01 UTC
**Describe the bug**
Hello, upon attempting to import my assignment, it has been hanging for approximately 45 minutes and not updating.

Found at this URL here: https://classroom.github.com/assignment-invitations/2c25c8f012b6e9cb69c8951ce3eebba2/setup

**To Reproduce**
Import an assignment per normal steps.
https://classroom.github.com/assignment-invitations/2c25c8f012b6e9cb69c8951ce3eebba2/setup

**Expected behavior**
The code should import in a timely manner, but isn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/38998433/68080597-ea71e800-fdcc-11e9-9f2d-c26f15a0cac8.png)

**Comment by THSCS** [comment] 2019-11-05 19:38
Had a similar issue, but only with some students. It seemed to usually be the same few students.

I switched to using templates instead of cloning the full repo and that seems to have cleared it up. Plus, it's much faster for the students that work anyway.

**Comment by d12** [comment] 2019-12-06 16:54
The issue is solved by using template repos. We'll deprecate the old method of importing soon, closing this issue.

**Closed by d12** 2019-12-06 16:54 UTC
