### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by bhirtzer** [education/classroom#1513] opened 2018-08-28 13:17 UTC
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried creating a GitHub repository in GitHub classroom

#### What happened (include screenshot if you can) ?
_It appears that here is an error along the way and it stops creating when it reaches the halfway mark
![github error](https://user-images.githubusercontent.com/17343959/44725344-ac778680-aa9a-11e8-83d0-5e7125e3407e.JPG)

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

I login and then paste the provided link in the URL box.

**Comment by BenEmdon** [comment] 2018-08-28 13:41
Hey @bhirtzer, thanks for writing in with a detailed issue. 🙌 
This appears to be a bug. I'll investigate what's causing this bug.

#### Things you can do to work around this issue:
Please report this to the admin of your classroom (A teacher or TA), and ask them to create a new repo for you manually.

Sorry for the inconvenience.

**Comment by BenEmdon** [comment] 2018-08-28 13:42
Duplicate of #1502

**Closed by BenEmdon** 2018-08-28 13:42 UTC
Labels: :beetle: bug, create/import repo flow
