### ISSUE TITLE
Github import project hanging

### ISSUE THREAD

**Issue by nickjones1996** [education/classroom#1780] opened 2019-02-25 00:13 UTC
**Describe the bug**
Importing starter code for project hangs, been over 3 hours and still stuck on "Importing starter code..."
**To Reproduce**
1. Go to 'https://classroom.github.com/a/2QeibC0F'
2. Click on 'import project'
3. Project import hangs, progress bar and text do not change for 3+ hours. 

**Expected behavior**
I expected to click import project, to wait a couple of minutes, and then be redirected to the new repo so I could clone it.

**Comment by BenEmdon** [comment] 2019-02-25 03:19
Duplicate of #1778

**Comment by BenEmdon** [comment] 2019-02-28 14:24
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:24 UTC
Labels: duplicate
