### ISSUE TITLE
Classroom created repos stall

### ISSUE THREAD

**Issue by kbinney** [education/classroom#1776] opened 2019-02-23 17:37 UTC
Students attempt to accept an assignment, which is initialized with a public repo owned by the our organization, but after many hours (ie 8+) the assignment still shows as initializing.

**To Reproduce**
Attempt to accept the "ps 3" assignment for cs51. It doesn't happen every time, but enough that some students are not able to get started on work.

**Expected behavior**
We expect the repos to initialize in a reasonable amount of time, ie a few minutes. 

**Additional context**
Approximately 250 students accept the assignment in the span of roughly 3-5 days. This problem has occurred with  our "ps3" and "ps4" assignments. It also happens with nearly every "lab" assignment, where about 150 students attempt to simultaneously accept the assignment. The starter repo is owned by our organization and is public. Student's repositories are set to be private and they are not their own admins. These assignments are individual assignments.

**Comment by kbinney** [comment] 2019-02-24 01:21
<img width="1368" alt="screen shot 2019-02-23 at 12 42 41 pm" src="https://user-images.githubusercontent.com/19810267/53293770-96782380-37a8-11e9-8f4a-1451f3b12a27.png">
Update: Above is where it stalls for many hours / indefinitely.

**Comment by BenEmdon** [comment] 2019-02-25 03:43
Duplicate of #1778 
Please look [there](https://github.com/education/classroom/issues/1778) for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:25
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:25 UTC
Labels: duplicate
