### ISSUE TITLE
Problem in accpeting the assignment

### ISSUE THREAD

**Issue by chenkuan94** [education/classroom#1272] opened 2018-02-15 21:08 UTC
The site always says "We were not able to add you to the Assignment as a collaborator, please try again." I don't know the reason. Could someone help me ?

**Comment by filalano** [comment] 2018-02-16 14:59
@Kadaaran, this problem still exists in our assignment. https://classroom.github.com/a/UvQiVcNw -- Can somebody help? Why is this issue closed?

**Comment by Kadaaran** [comment] 2018-02-16 15:16
Hi @filalano ,

This issue is a duplicate of #1271 that's why I am closing it as well.
But don't worry I'm well aware of the issue.
I am just gathering all the comments about one issue in a same place so it'll be easier to gather comments and fix it. 
You may go into #1271 to talk about the assignments issue so we can get your comments and explanations about the issue.

**Comment by Kadaaran** [comment] 2018-02-16 15:16
Hi @filalano ,

This issue is a duplicate of #1271 that's why I am closing it as well.
But don't worry I'm well aware of the issue.
I am just gathering all the comments about one issue in a same place so it'll be easier to gather comments and fix it. 
You may go into #1271 to talk about the assignments issue so we can get your comments and explanations about the issue.

**Closed by Kadaaran** 2018-02-16 15:16 UTC
