### ISSUE TITLE
Unable to fork a repository

### ISSUE THREAD

**Issue by aknilosey** [education/classroom#1282] opened 2018-02-18 21:29 UTC
When I try to fork a repo using GitHUb classroom it gives an error saying "We were not able to add you to the Assignment as a collaborator, please try again." although I am added as a collaborator.

**Comment by hoyosjs** [comment] 2018-02-19 01:27
See #1271

**Comment by Kadaaran** [comment] 2018-02-19 09:00
Duplicate of #1271

**Closed by Kadaaran** 2018-02-19 09:00 UTC
Labels: duplicate
