### ISSUE TITLE
Importing starter code takes forever

### ISSUE THREAD

**Issue by mainland** [education/classroom#1774] opened 2019-02-22 23:57 UTC
I am currently experiencing the same issue as #1623 for the DrexelCS360 organization. Is there a GitHub service outage?

**Comment by dshean** [comment] 2019-02-23 00:40
I'm also experiencing this.  Worked normally for 4 out of 12 students.  The rest still have a stuck progress bar.  I deleted one student's repo, and she tried to re-accept the assignment.  Same problem.

**Comment by belgort-clark** [comment] 2019-02-23 00:45
Same here. Students are contacting me with these same errors. Let me know how I can help.

**Comment by klancasterprof** [comment] 2019-02-23 01:09
A student just contacted me about this - 2 hours and counting. I also noticed that just looking at a previous assignment I had given took a couple of minutes to load, even though there were only about 40 students.

**Comment by amcdonald714** [comment] 2019-02-23 01:56
I have also had multiple students contact me with this issue over the last few hours.

**Comment by iakopatran** [comment] 2019-02-23 03:22
I am also experiencing this issue for the cal-cs184 class. Assistance or further information would be appreciated.

**Comment by A-Alaa** [comment] 2019-02-23 05:19
The issue is still persisting for my classroom.

**Comment by an-ju** [comment] 2019-02-23 05:51
We are having the same issue.

**Comment by Hugo0** [comment] 2019-02-24 23:52
I'm having the same issue here.

**Comment by BenEmdon** [comment] 2019-02-25 03:44
Duplicate of #1778 
Please look there for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:25
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:25 UTC
Labels: duplicate
