### ISSUE TITLE
Importing Starter Code never finishes

### ISSUE THREAD

**Issue by moritzge** [education/classroom#1772] opened 2019-02-22 20:00 UTC
**Describe the bug**
When the students click on the invite link for an assignment, a new repo is created, but the import takes forever/never ends.

**To Reproduce**
1. open invite link
2. repo gets created
3. import never ends
4. when import is canceled, repo is empty

**Expected behavior**
Starter code imported correctly.

**Screenshots**
<img width="1071" alt="grafik" src="https://user-images.githubusercontent.com/2479609/53267801-99114500-36e4-11e9-8117-537c2300436a.png">

**Additional context**
Classroom: https://classroom.github.com/classrooms/47527793-compfabrob19
Assignement: https://classroom.github.com/classrooms/47527793-compfabrob19/assignments/comp-fab-a0
Main repo: https://github.com/computational-robotics-lab/comp-fab-a0
Example student repo: https://github.com/computational-robotics-lab/comp-fab-a0-moritzgetest/import

Other than that bug, github classroom is a great tool and I enjoy using it! Thanks!

**Comment by belgort-clark** [comment] 2019-02-23 06:19
Same here.

**Comment by belgort-clark** [comment] 2019-02-23 15:44
It's still not working as of Saturday morning

**Comment by BenEmdon** [comment] 2019-02-25 03:44
Duplicate of #1778 
Please look there for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-25 03:56
@moritzge I have just confirmed that imports are back up and running again on your classroom. I am going to go ahead and close this.

**Closed by BenEmdon** 2019-02-25 03:56 UTC
Labels: duplicate

**Comment by moritzge** [comment] 2019-02-25 09:57
@BenEmdon Great! Thanks a lot.
