### ISSUE TITLE
Error creating new assignments

### ISSUE THREAD

**Issue by rsardinas** [education/classroom#1235] opened 2018-01-18 22:56 UTC
[github_assgn_error.docx](https://github.com/education/classroom/files/1644717/github_assgn_error.docx)

Hello, I'm getting an error where I can't create any assignments. I've attached a word document with a screenshot of what I see after I attempt to create an assignment.

Also, I can't delete assignments (or don't know how). Any help would be appreciated. I'd like to make the next assignment for them next week!

Thanks in advance,

Rodrigo

**Comment by tarebyte** [comment] 2018-01-19 02:06
Duplicate of https://github.com/education/classroom/issues/1234

**Closed by tarebyte** 2018-01-19 02:06 UTC
