### ISSUE TITLE
Repository setup progressbar hangs at "Importing starter code..."

### ISSUE THREAD

**Issue by hroncok** [education/classroom#1777] opened 2019-02-24 11:28 UTC
**Describe the bug**
The repository setup progressbar when clicking on assignment link hangs forever.

**To Reproduce**
1. Go to classroom.github.com
2. In a classroom, create a new (individual) assignment
3. Use **Add your starter code from GitHub**
4. Make sure to **Enable assignment invitation URL**
5. Later, click on the assignment invitation URL and follow the steps

**Expected behavior**
After the repo is created, you are redirected to it or see a message that says where you should continue.

**Screenshots**

Hangs here. Repo is created (but stuck at importing), but the progressbar just hangs. Reproduced in Chromium, but probably also happens in Firefox.

![_](https://user-images.githubusercontent.com/2401856/53298506-60ca4d80-382f-11e9-9804-5b3aa4411395.png)

cc @syky27 @mmajko @Zubcz

This was already once reported at https://github.com/education/classroom/issues/1636
But I cannot reopen it.

Our hooks at https://github.com/organizations/3dprintfit/settings/hooks

![_](https://user-images.githubusercontent.com/2401856/53298519-8bb4a180-382f-11e9-8b40-221f68ea95b5.png)

**Comment by hroncok** [comment] 2019-02-24 11:28
This time, the repository is not ready:

![_](https://user-images.githubusercontent.com/2401856/53298531-bacb1300-382f-11e9-810c-81c05541dfa3.png)

**Comment by hroncok** [comment] 2019-02-24 12:24
deleting and starting over helped this time :( a haisenbug

**Comment by snadi** [comment] 2019-02-24 14:50
I have the same problem. What I do is cancel the import and manually commit and push the starter code to the student's repo. The thing is this does't happen with every student though.

**Comment by BenEmdon** [comment] 2019-02-25 03:21
Duplicate of #1778 
Please look [there](https://github.com/education/classroom/issues/1778) for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:24
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:24 UTC
Labels: duplicate
