### ISSUE TITLE
Not able to add you to the assigment Error

### ISSUE THREAD

**Issue by ivanjimenez** [education/classroom#1277] opened 2018-02-16 17:24 UTC
Dear friends of classroom:

I use google classroom assignments for my students. All worked fine until a couple of students tried to accept an assignment by link. But they couldn't with this error output:
`We were not able to add you to the Assignment as a collaborator, please try again.` 

I have an organization with a team, and other users of this team accepted the assignment without problem. I tried to do the same with another user. I remove this user from the team and after this, another invitation was sent. I tried to accept the assignment without success. Also, I did other new assignments and remove the user from the team without any access too. 

This is my link for assignment:
[assignment link](https://classroom.github.com/a/BXzT5MLX)

Could you give some help in order to solve this issue.

Thanks a lot
Kind Regards.

**Comment by Kadaaran** [comment] 2018-02-16 17:39
Hi @ivanjimenez !

We are aware of this issue and are trying to fix it. 
Unfortunately your issue is a duplicate of #1271 
I'm going to close this one and invite you to go to #1271 to get more informations and to be updated regarding this issue.

Thank you for reporting this issue.

**Closed** 2018-02-16 17:39 UTC
Labels: duplicate

**Comment by ivanjimenez** [comment] 2018-02-16 17:47
I appreciate your quick response. So, I'm waiting for the solution. 
Best regards.
