### ISSUE TITLE
Token authentication & duplicate repos

### ISSUE THREAD

**Issue by dogfishbar** [education/classroom#1286] opened 2018-02-21 22:02 UTC
Hello. I am having a problem with organization BC-CSCI1102. The organization has 58 Members enrolled with 3 Owners, myself & 2 TAs. Many of us are getting token errors at odd intervals:

> "Cannot retrieve this organizations repo plan, please reauthenticate your token"

And when students accept Assignments, they are often getting duplicates repos made. The number of duplicates can vary from 1 to as many as 5:
![image](https://user-images.githubusercontent.com/1794931/36507704-985c9a6a-1728-11e8-94fc-8cd92d460cf7.png)

I believe that this problem is related to issue #664:

https://github.com/education/classroom/issues/664

I hope someone can give us some guidance on this.
Thanks!
Bob Muller

**Comment by Kadaaran** [comment] 2018-02-22 13:08
Hi @dogfishbar ,

Thank you for reporting this issue
Did you change the organization's owner recently (for example one of the organization owners left)? 🤔

**Comment by Kadaaran** [comment] 2018-02-22 13:09
Hi @dogfishbar ,

This on is indeed a duplicate of #664 I am closing this one and will answer you in #664 thanks !

**Closed by Kadaaran** 2018-02-22 13:09 UTC
Labels: duplicate
