### ISSUE TITLE
empty assignment reporsitory

### ISSUE THREAD

**Issue by javier-op** [education/classroom#786] opened 2016-11-17 20:02 UTC
after clicking the assignment link, it just creat an empty repository, no starting files.

**Comment by tarebyte** [comment] 2016-11-17 20:27
@javier-op can you give me a little context?

Did the assignment have a starter code repository that it was supposed to use?

**Comment by javier-op** [comment] 2016-11-17 20:34
Yes, it's supposed to have a .tex and a .pdf file with the instructions. I
used a link provided by my teacher to create the repository but when in the
"Preparing your new repository" page I got redirected to a server error and
an empty repository was created. I contacted my teacher to try accepting
the assignment again but I'm currently stucked in "Preparing your new
repository".

**Comment by tarebyte** [comment] 2016-11-17 20:38
@javier-op can you email me tarebyte @ github dot com and I can try to help you out.

Thanks!

**Comment by dhowe** [comment] 2016-11-18 04:26
This is a regular occurrence, documented in other tickets (#784 and others), where somewhere between 1-5% of all repositories created are empty like this.  Until this [big] bug is fixed, you (the instructor) need to push the start-code into the students repo manually

**Comment by lhscompsci** [comment] 2016-11-18 17:53
This is the screen I have a bout 1 in 200 times where things get stuck:
![image](https://cloud.githubusercontent.com/assets/5266774/20440361/6a4e04aa-ad85-11e6-8361-02d789a95f51.png)
I don't know if this is the same error but I couldn't even delete the bad repository for the first student this happened to.  We had to just have a completely separate outside-of-classroom repo for him at the end of it all.
Thanks!

**Comment by nwoodthorpe** [comment] 2017-05-23 17:22
Duplicate of #772

**Closed by nwoodthorpe** 2017-05-23 17:22 UTC
