### ISSUE TITLE
Assignment spontaneously disappeared along with associated submitted repos

### ISSUE THREAD

**Issue by brandonrich** [education/classroom#431] opened 2016-01-15 15:07 UTC
Details here on this Google Doc.  
https://docs.google.com/document/d/1U6JJUgFrfhNG0J4ubPtNCXt31gPY-7T613HpOVLI9_Y/edit?usp=sharing

My org is called NDMobileApps.  Yesterday I created an assignment called Assignment0 for testing submission with my students.  Two had already submitted repos and I browsed them.  Refreshing the org page this morning, they vanished, and do not appear in search.  The news feed still shows their activity, though -- only all links go to 404s.  My Classroom page looks as though the assignment is just gone.  Invitation link serves up a 500 error:  https://classroom.github.com/assignment-invitations/c5194fe104c05bc4ac22cba60cfe76d3

This is the worst possible version control experience for my students.  I prefer to use GitHub, but it can't just delete repos!

**Comment by tarebyte** [comment] 2016-01-15 15:12
@brandonrich we don't randomly delete assignments nor do we delete repositories.

I'm going to investigate this today.

I will keep you posted with my findings.

**Comment by brandonrich** [comment] 2016-01-15 15:14
Thanks for the quick reply.  I assume the content is still lurking somewhere.  I just need to be confident in this going forward.  I haven't touched the classroom setup since I sent the assignment; I only browsed the repos in the org.  Thank you!

**Comment by johndbritton** [comment] 2016-01-15 15:16
I've restored the repositories to your organization account. Did you happen to reset your organization in Classroom for GitHub?

**Comment by johndbritton** [comment] 2016-01-15 15:19
It looks like you deleted the `Assignment0` assignment from your account in Classroom for GitHub. This made the invitation link stop working and removed the repositories from your account on GitHub.

Please let us know what other actions you took in Classroom for GitHub.

**Comment by brandonrich** [comment] 2016-01-15 15:20
No, definitely not.  Didn't touch a thing other than to refresh my org page and browse submissions.  

Repos are back, thanks, but Assignment0 is still gone and the related invite link broken.

Somehow Assignment0 got removed/deleted and took the repos -- I'm guessing -- out the org.

**Comment by brandonrich** [comment] 2016-01-15 15:21
I don't even know how to delete assignments, which is why the three test assignments are still there.

**Comment by johndbritton** [comment] 2016-01-15 15:22
> Somehow Assignment0 got removed/deleted and took the repos -- I'm guessing -- out the org... Assignment0 is still gone and the related invite link broken.

Yes, this is what it looks like on our end. You can create a new assignment in Classroom for GitHub to generate a new invitation link. I don't know what could have caused `Assignment0` to get deleted from Classroom for GitHub other than manually deleting the assingnment.

> I don't even know how to delete assignments, which is why the three test assignments are still there.

If you click on the assignment and then you use the `settings` button, you are able to delete it from that page.

**Comment by brandonrich** [comment] 2016-01-15 15:26
I'm glad the submissions are back, thank you.  A few things:

- If I create another assignment by the same name, do you anticipate any issue?
- Do you have logs that indicate a delete action definitely took place?  If so, any indication as to the source?
- Were the repos accessible to their creators the whole time, even when they were not visible to the org?

**Comment by tarebyte** [comment] 2016-01-15 15:27
@brandonrich is anyone else have access to the Classroom apart from you?

**Comment by brandonrich** [comment] 2016-01-15 15:29
No, I'm the only owner.

On a related note, I thought students had to accept an invite to the org when they take an assignment, so why does it still show I'm the only member of the org?

**Comment by johndbritton** [comment] 2016-01-15 15:30
> If I create another assignment by the same name, do you anticipate any issue?

No, you should be able to create a new assignment with the same name. The existing submissions will not be associated with the new assignment, however.

> Do you have logs that indicate a delete action definitely took place? If so, any indication as to the source?... Were the repos accessible to their creators the whole time, even when they were not visible to the org?

Can you follow up by emailing `education@github.com`, that way we can discus account specific issues in private.

> On a related note, I thought students had to accept an invite to the org when they take an assignment, so why does it still show I'm the only member of the org?

Students are granted access to the repository as outside collaborators, only group assignments require them to become organization members.

**Comment by brandonrich** [comment] 2016-01-15 15:32
I'll follow up via email on the assignment deletion.

Re: outside collaborators, I guessed at that, but the Outside Collaborators tab says "No one outside of the organization has access to its repositories."

**Comment by johndbritton** [comment] 2016-01-15 15:33
> No one outside of the organization has access to its repositories.

Outside collaborators are able to access repositories that they are assigned to, but no other repositories.

**Comment by johndbritton** [comment] 2016-01-15 15:43
The repositories have been restored. If we find that this was caused by a bug, I'll open another issue with full details.

**Closed by johndbritton** 2016-01-15 15:43 UTC
Labels: report

**Comment by johndbritton** [comment] 2016-01-15 17:02
Resolved in https://github.com/education/classroom/pull/433
