### ISSUE TITLE
Can't add second classroom

### ISSUE THREAD

**Issue by dmgatti** [education/classroom#1721] opened 2018-12-17 19:42 UTC
**Describe the bug**
I have created one classroom and associated it with my organization. I cannot add a second classroom because it stops me on the 'Select an organization for your new classroom' screen. My organization is greyed out and the tool tip over it says '@dmgatti has already added this organization to GitHub Classroom'. It may be that I misunderstand how to add a new classroom.

**To Reproduce**
1. Go to 'https://classroom.github.com/classrooms'
2. Click on 'New classroom'
3. Try to click on  '@CollegeoftheAtlantic'.

However, you can't select this organization because it is greyed out.
Thanks!

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ccannon94** [comment] 2018-12-18 15:01
@dmgatti there is a limit of 1 classroom per organization. The recommended setup is to have 1 organization and 1 classroom per class per semester. As a lab instructor, I find this helps keep things organized moving from semester to semester. Whether or not you want to use a different organization for each section of a class is up to you, we use 1 organization for all 4 sections. Anyway, hope this helps! My expectation is the classroom team will likely close this as not a bug.

If you haven't already, consider checking out GitHub Education's [teacher training program](https://education.github.com/advisors) to learn more about using GitHub and Classroom with your students.

**Comment by dmgatti** [comment] 2018-12-19 14:20
Got it. I suspected that it might be an intentional policy. I would suggest that the message in the tool tip over the organization mention the one-classoom-per-organization rule.


Thanks!

Dan

________________________________

**Comment by BenEmdon** [comment] 2019-01-18 21:06
Hey @dmgatti 👋  

As @ccannon94 mentioned, there is a limit of 1 classroom per organization. 

This is definitely not ideal and we are working on allowing organizations to have multiple classrooms (but that change is still in the works). 

Thanks @ccannon94 for answering and providing some advice 👏 

Im going to go ahead and close this issue. If either experience a bug with classroom, be sure to open a new issue!

**Closed by BenEmdon** 2019-01-18 21:06 UTC
