### ISSUE TITLE
"Cannot retrieve this organizations repo plan, please reauthenticate your token."

### ISSUE THREAD

**Issue by lucaquerella** [education/classroom#464] opened 2016-02-20 05:38 UTC
Some of my colleges cannot ask one of my assignment. 
They get this error: "Cannot retrieve this organizations repo plan, please reauthenticate your token.".
The assignment works for other colleges. 
They already try to login/logout both from github and from classroom. It didn't help.

**Comment by ksuderman** [comment] 2016-02-24 04:04
I had the same problem [1].  I finally resolved it by recreating the assignment with a different name.

REFERENCES
1. https://github.com/education/teachers/issues/46

**Comment by johndbritton** [comment] 2016-03-14 19:16
> They get this error: "Cannot retrieve this organizations repo plan, please reauthenticate your token.".

@lucaquerella This means that the user has removed our access to their account. The issue can be resolved by logging out and logging back in. When the user logs in again, they should be prompted to give Classroom access to their GitHub account.

**Comment by ksuderman** [comment] 2016-03-16 19:13
@johndbritton @tarebyte This should be re-opened as it is still an ongoing issue... I am experiencing it again.

Logging out and logging back in again does ***not*** solve the problem. Unfortunately my previous work around of recreating the assignment hasn't worked either, and revoking the Classroom OAuth token from my profile and reauthorizing has no effect.  In fact after revoking the OAuth token and re-authorizing I received the "Cannot retrieve this organizations repo plan" error when I tried to re-create the assignment.  A second attempt to create the assignment resulted in the message "You don't have permission to perform the desired action" (or something similar).  I revoked the OAuth token again and have been able re-create the assignment, but I still get the above error when trying to accept the assignment invitation.

Some related notes;

+ when I first viewed the assignment on Classroom it showed the message that there were no repositories for the assignment.  Yet when I visit our organization I see that one student repository has been created.
+ when I tried to accept the assignment I received the above error message, but shortly thereafter received an email saying my repository had been created, but I received a 404 when following the link in the email.

**Comment by johndbritton** [comment] 2016-03-16 20:27
@ksuderman Thanks for letting us know. @tarebyte can you dig into this?

**Comment by tarebyte** [comment] 2016-03-16 20:38
Hey @ksuderman the other owner of your classroom @nancyide doesn't not have the proper token scopes. @nancyide has the scope of `user:email` which is not enough for assignment creation.

This is a duplicate of #461 and will be resolved once we close #445.

@ksuderman can you have @nancyide log back in as a teacher at htttps://classroom.github.com and see if that fixes the issue?

Thanks!

**Comment by ksuderman** [comment] 2016-03-16 20:50
@tarebyte I will have @nancyide log back in ASAP.  However, will Nancy not having the proper token scopes prevent students from accepting the assignment invitation?

Do you have an ETA on when #445 will be closed?

**Comment by tarebyte** [comment] 2016-03-16 20:53
> However, will Nancy not having the proper token scopes prevent students from accepting the assignment invitation?

Yes that is correct.

@ksuderman there isn't really a good way to fix this, but I'm hacking on something tonight which should at least try and help prevent this.

**Comment by ksuderman** [comment] 2016-03-16 22:51
@tarebyte having Nancy log back in to https://classroom.github.com fixed the problem.  Next assignment I will be sure to have both of use log out/in from the Classroom.  However, from what @johndbritton says in education/teachers#46 it seems that the simple act of testing the assignment checkout process breaks the assignment checkout process!

**Comment by johndbritton** [comment] 2016-03-16 23:48
> it seems that the simple act of testing the assignment checkout process breaks the assignment checkout process!

Yes, that's exactly the case. The issue is a bit complicated, but it's due to the fact that we ask for less permissions of student users and since the user isn't logged in when they visit the accept assignment page we have to log in and request permissions again when the teacher tests out the accepting flow. When we get the permissions in this case they are reduced and we can no longer make repositories for the students.

**Closed** 2016-05-27 13:00 UTC
Labels: report
