### ISSUE TITLE
Students cannot accept assignment

### ISSUE THREAD

**Issue by laleese** [education/classroom#1275] opened 2018-02-15 23:48 UTC
I created a new assignment today. You can find it at: https://classroom.github.com/a/UvQiVcNw
My test student gets the message "We were not able to add you to the Assignment as a collaborator, please try again." This is our third assignment, but the first one to have this problem. 

Can you help?

**Comment by Kadaaran** [comment] 2018-02-16 14:24
Duplicate of #1272

**Closed by Kadaaran** 2018-02-16 14:24 UTC
Labels: duplicate

**Comment by filalano** [comment] 2018-02-16 14:56
But the problem still exists. why is this issue closed?

**Comment by Kadaaran** [comment] 2018-02-16 15:11
Hi @filalano ,

Yes the problem still exists. This issue is a duplicate fo the #1272 that's why I closed it (to avoid having multiple issues open for the same issue)
