### ISSUE TITLE
Importing starter code hang

### ISSUE THREAD

**Issue by Unco3892** [education/classroom#1785] opened 2019-02-25 14:51 UTC
Joining the assignments for the two links of the class freezes at the end for many students, Please suggest us what should be done.

https://classroom.github.com/a/Q-Gcc4Hq
https://classroom.github.com/classrooms/22398800-education-by-alphacruncher/assignments/DataAnalytics-hec-ss19
![image](https://user-images.githubusercontent.com/47745523/53345371-10c5b680-3915-11e9-93ac-2bfd524436b9.png)

**Comment by khmchk** [comment] 2019-02-25 14:57
The same problem!

**Comment by stanislasprog** [comment] 2019-02-25 14:58
same problem

**Comment by BenEmdon** [comment] 2019-02-25 17:05
## Duplicate of #1778 
Please look at #1778 for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:24
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:24 UTC
Labels: duplicate
