### ISSUE TITLE
Error when trying to join existing team

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#171] opened 2015-09-02 15:23 UTC
I get the following error when I try to join an existing team:

<img width="995" alt="screen shot 2015-09-02 at 4 19 58 pm" src="https://cloud.githubusercontent.com/assets/123345/9635542/ded2ae88-518e-11e5-8615-12de679cc87a.png">

**Comment by johndbritton** [comment] 2015-09-03 12:41
I haven't been able to reproduce this.

**Comment by tarebyte** [comment] 2015-09-03 12:50
I'll close this for now. Feel free to reopen if this creeps up again.

**Comment by johndbritton** [comment] 2015-09-08 19:28
I just reproduced this, but don't think I did anything differently.

**Comment by johndbritton** [comment] 2015-09-08 19:33
I think this happens if you focus the text area and then select something from the dropdown. Pressing submit a second time succeeds.

**Comment by tarebyte** [comment] 2015-09-15 03:37
@johndbritton I can't reproduce your error with the steps that you gave me.

**Comment by johndbritton** [comment] 2015-09-15 12:25
@tarebyte I understand, I've had trouble reproducing it myself. Labeled this as a bug and we can leave it open in case anyone else experiences the same issue. If we don't get any more reports and don't experience it ourselves for a while then we'll close this and move on.

I don't think it's worth spending more time to resolve this until we have more reports and can reliably reproduce the issue.

**Comment by johndbritton** [comment] 2015-09-24 14:24
I just reproduced this again, perhaps in a different case: After deleting an old classroom, I reconnected and tried to accept an assignment. It tried to create a team named "johndbritton" which wasn't removed when I "reset and removed" my previous classroom. This is likely due to a failed deletion job.

**Comment by johndbritton** [comment] 2015-09-24 14:25
Also could be caused by folks recreating things faster than the job runs.

**Comment by johndbritton** [comment] 2015-10-04 15:32
I believe this was resolved with #277.

**Comment by johndbritton** [comment] 2015-10-12 11:28
@tarebyte finally reproduced this one

**Comment by tarebyte** [comment] 2015-12-19 07:24
I'm going to close this again until I can remember how to reproduce it.

**Closed by tarebyte** 2015-12-19 07:24 UTC
Labels: bug
