### ISSUE TITLE
Repository import occasionally hangs for dozens of minutes.

### ISSUE THREAD

**Issue by rkomorn** [education/classroom#1570] opened 2018-09-16 19:21 UTC
**Describe the bug**
Import

**To Reproduce**
1. Accept an assignment
2. Wait for assignment to be cloned.

https://github.com/hackbrightassessments/skills-object-orientation-salazardenise was the result of accepting an assignment before 12:06pm today, but by 12:16 it was still in the process of being set up. I had to cancel it so our student could get started on their work.

**Expected behavior**
It should create the new repository, quickly. There is only one file and one commit in that repository's history. There's no reason whatsoever it should take more than a few seconds.

**Additional context**
This is at least the second time we've noticed issues with how slow repos are created and set up GitHub classroom. Our students complete assignments over the weekend and this kind of stuff means that:

- they are on their own while waiting for the repo to import properly

- they have to reach out to us in order to understand what's going on, which not only slows them down and makes it harder for them to complete their homework but also interrupts our instructors' weekends and forces us to try and troubleshoot github classroom issues that are completely opaque to us.

**Comment by johndbritton** [comment] 2018-09-17 12:53
@rkomorn We recently changed the way repository creation is handled which should result in a much quicker and more reliable experience.

@BenEmdon can you take a look at this and see what might have been the cause?

**Comment by johndbritton** [comment] 2018-09-17 12:55
Specifically, it'd be good to know what caused the slow creation, a few things I might guess:

* The import job started and completed, but we missed the `complete` webhook event
* The import job took a long time (not Classroom) and we should escalate the issue to our platform team.

**Comment by BenEmdon** [comment] 2018-09-17 13:30
@rkomorn when you said:
> I had to cancel it so our student could get started on their work.

Did you mean that you stopped the source import manually by clicking `cancel`? 
![image](https://user-images.githubusercontent.com/820984/45320204-dbf4ad00-b4f6-11e8-8097-afca5bc259ab.png)

If not, what did you do specifically to cancel the creating the assignment?

**Comment by rkomorn** [comment] 2018-09-17 13:32
@BenEmdon Precisely that button, yes.

**Comment by BenEmdon** [comment] 2018-09-17 13:45
It appears that the problem was a that the import job took a long time. Like @johndbritton said, this isn't handled by the Classroom team so we will have to escalate the problem to our platform team.

To give you some context on this issue, the source importer queues repository imports. This means if theres a high load of repository imports, the source importer will take some time to work its way through the queue. 

@rkomorn To ensure this gets handled directly I would advise you to [contact GitHub support](url
https://github.com/contact) and say that your students have experienced some slow import times.

**Comment by rkomorn** [comment] 2018-09-17 13:49
@BenEmdon Will do. Just to be clear, when you talk about a high load of repo imports, you're talking about globally having a lot of requests for imports, right? Not with our repo importing too much stuff (since it's importing a single file)?

**Comment by BenEmdon** [comment] 2018-09-17 14:07
> Just to be clear, when you talk about a high load of repo imports, you're talking about globally having a lot of requests for imports, right? Not with our repo importing too much stuff (since it's importing a single file)?

Yes, I mean the global volume of import requests. A single file import such as yours shouldn't take so long to import.

**Comment by johndbritton** [comment] 2018-09-17 17:02
I'm going to close this issue as we've identified the source and escalated via the appropriate internal channel. This was not an issue with GitHub Classroom, it was a load issue on the GitHub Source . mport API.

@rkomorn thanks very much for reporting this.

**Closed by johndbritton** 2018-09-17 17:02 UTC
