### ISSUE TITLE
Unable to navigate assignment pages

### ISSUE THREAD

**Issue by ProfDema** [education/classroom#1322] opened 2018-03-24 00:27 UTC
I have a github classroom assignment.
Page 1 is here:
https://classroom.github.com/classrooms/34876003-utmcsc301/group-assignments/a3?page=1
Although there are three pages reported, I am unable to visit pages 2 and 3

Thank you.

**Comment by Kadaaran** [comment] 2018-03-26 09:42
Hi @ProfDema , your issues is a duplicate of #1303  
I invite you to go there to be updated about it. Thank you.

**Closed by Kadaaran** 2018-03-26 09:42 UTC
Labels: duplicate
