### ISSUE TITLE
Importing Starter code is hanging

### ISSUE THREAD

**Issue by wschilling** [education/classroom#1795] opened 2019-03-12 15:32 UTC
**Describe the bug**
When a user joins a classroom project, the starter code import is hanging.  This leave the project in an unusable state.

**To Reproduce**
This has occurred randomly on about 50% of my students projects and is occurring  to me.  To reproduce, simply join a classroom with a given assignment.

This same issue also occurred to a colleagues class last week on Thursday.

![BrokenProjectImport](https://user-images.githubusercontent.com/28993106/54213192-04636100-44b2-11e9-8cac-fac7bb4e01b4.PNG)

**Comment by mosser** [comment] 2019-03-12 19:32
I have the very same issue in my class. I had to do manually the import so that the student can work (cloning the empty repo on my computer, copying the starter code, comiting and pushing it to origin)

**Comment by Nate-weeks** [comment] 2019-03-12 19:43
I'm having the exact same issue.  None of my students were able to import starter code today.

**Comment by joeparislbcc** [comment] 2019-04-02 21:04
I'm having this issue right now.

**Comment by pwmarcz** [comment] 2019-04-04 07:09
This is happening routinely in our organization.

**Comment by dsparkin** [comment] 2019-04-19 18:36
Also happening for all assignments in my classroom.
Example invite: https://classroom.github.com/a/bcUGSFD-

**Comment by shaunakpp** [comment] 2019-06-26 23:09
This is a duplicate of #1591 and we are tracking this issue there. Closing this issue in favour of #1591. I've also added a "slow code import" tag so that we can reference this issue.

**Closed by shaunakpp** 2019-06-26 23:09 UTC
Labels: slow code import
