### ISSUE TITLE
Assignment invitation links either return 500 or import hangs

### ISSUE THREAD

**Issue by clwyatt** [education/classroom#1530] opened 2018-08-31 13:47 UTC
##
#### What you were trying to do ?
On August 30 at approx 11 am around 50 students where trying to accept an assignment invitation for an in class assignment. They were provided with the link that they were clicking on in their browsers.

#### What happened (include screenshot if you can) ?
For about 30/50 of them the link showed a 500 Server Error code, or the import hung. In the latter case sometimes the import succeeded but the progress did not change. Just going to the repo showed it was imported ok. About 25/50 would continually get the 500 error. 

#### Step-by-step reproduction instructions
This is hard to reproduce as it seems to be a loading issue. It has happened twice within the last week with varying severity. Usually after about 30 min the links will start to work again.

#### Alternative workaround
Is it possible for me to accept a link on their behalf which I can spread out over a few hours before class starts?

**Comment by BenEmdon** [comment] 2018-08-31 13:53
Hey @clwyatt 👋 thanks for writing in.

Yesterday we experienced some downtime after there was a unexpected problem with our hosting service (Heroku). Fortunately we found a workaround within the hour, and hopefully it doesn't happen again.

Classroom should behave as expected. If you experience any unexpected behavior please open another issue.

I'll close this issue since we resolved the downtime.

**Closed by BenEmdon** 2018-08-31 13:53 UTC
