### ISSUE TITLE
Student's get stuck importing assignment in classroom

### ISSUE THREAD

**Issue by bwproud** [education/classroom#1786] opened 2019-02-27 19:22 UTC
**Describe the bug**
In this lab 5 students couldn't import their copy of the assignment: https://classroom.github.com/a/Hl53rYF1
**To Reproduce**

1. Accept assignment assignment: https://classroom.github.com/a/Hl53rYF1
3. Begin importing and copying repository
4. Some students get stuck

**Expected behavior**
All the students could import the assignment to their github account.

**Comment by BenEmdon** [comment] 2019-02-27 23:14
## Duplicate of #1778 
Please look at #1778 for updates and information ☝️

**Comment by BenEmdon** [comment] 2019-02-28 14:24
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:24 UTC
Labels: duplicate
