### ISSUE TITLE
Deleted user still shows up in assignment group

### ISSUE THREAD

**Issue by jmflorezff** [education/classroom#1289] opened 2018-02-22 20:04 UTC
I have a user named @ghost in one of my groups and I can't remove them because they don't show up in the organization team management interface in github. I understand this is a deleted user from github, so that would explain why I can't see them there. They are taking up a space that is needed by an account that is actually active.

**Comment by Kadaaran** [comment] 2018-02-23 10:53
Hi @jmflorezff ,

Thank you for reporting this issue. It appears that it's a duplicate of #1216 
The PR #1254 to fix this issue will be on its way soon 🙏

**Closed by Kadaaran** 2018-02-23 10:53 UTC
