### ISSUE TITLE
Assignment repository setup hanging

### ISSUE THREAD

**Issue by timalcon** [education/classroom#2431] opened 2019-10-16 17:41 UTC
**Describe the bug**
I’m having several students report that when they try to set up an assignment repository, it just hangs, with no change in the progress bar. This is a new problem - it worked for them previously.

**To Reproduce**
1. Click on GitHub Classroom link
2. Click "Accept this assignment"
3. Wait in vain for progress bar to change
It doesn't happen for me, who owns the Classroom account, but started happening for students a day or two ago.

**Expected behavior**
The progress bar should complete and say "you're ready to go".

**Screenshots**
![20191016_1](https://user-images.githubusercontent.com/48735194/66942793-ade97280-effe-11e9-8592-5681df4587dd.png)

**Comment by dominicwhite** [comment] 2019-10-16 21:03
This is also happening for me. So far just one student out of a class of 20, but he also gets the same issue for another Github classroom invitation in another organization.

![Screenshot from 2019-10-16 16-54-50](https://user-images.githubusercontent.com/6020835/66958751-e442e400-f036-11e9-8b36-a8c42b5bbc61.png)

**Comment by kesttvanzyl** [comment] 2019-10-16 21:21
I am having the same issue. I have tried opening two assignments and both of them are stuck on the progress bar. I left the page open for about an hour and it is still just hanging without showing any progress in the progress bar.

**Comment by robwhess** [comment] 2019-10-16 21:23
Some of my students are also experiencing this.

**Comment by bulletshot60** [comment] 2019-10-16 22:26
One of my students @ELANE931 is also having an issue cloning his assignments so I've been manually creating the repos for him in the mean time.

**Comment by danwallach** [comment] 2019-10-17 12:56
This sounds like a common problem using the "original" clone link process. The new "template" process has been much more robust for me. Make sure you try that.

**Comment by bulletshot60** [comment] 2019-10-17 12:58
@danwallach My group has converted our classrooms over to the template system, and I still have a few random students that are having issues.

**Comment by robwhess** [comment] 2019-10-17 14:40
Yes, I can confirm that I'm also using template repos for my starter code, and students are still experiencing this problem.

When my students used to have a problem with repository creation hanging under the original non-template system, it was almost invariably the case that a repo had been created for them on GitHub, but for some reason the code had failed to import. To fix the problem, I could usually just go and delete the (empty) repo that was created for them, and then when they accepted the assignment a second time, everything would work fine.

In these last few instances, however, where the repo creation process hung using the new template repo system, there wasn't even a GitHub repo (empty or not) created for the students in question. This makes me think the hanging in this case is happening earlier in the repo creation process than it used to, maybe even on the client side, but at least before any GitHub API calls are made to actually create the new repo (or possibly there's a failure with those API calls themselves).

**Comment by stephaniegiang** [comment] 2019-10-17 15:11
@robwhess could you tell us the classroom name and assignment this is happening in?

**Comment by dominicwhite** [comment] 2019-10-17 19:13
I just had another student with the same issue in the Edge browser, but they were able to get their repository created by switching to Chrome.

**Comment by psybers** [comment] 2019-10-17 19:45
This is happening to me too.  The classroom is BGSU-CS-3060-F19.

**Comment by psybers** [comment] 2019-10-17 19:47
I can confirm switching from Edge to Chrome fixed it for my student.

**Comment by stephaniegiang** [comment] 2019-10-17 20:27
Has retrying after waiting for a bit helped anyone?

**Comment by dominicwhite** [comment] 2019-10-17 20:34
@stephaniegiang My first student was able to get it working after he went home, but I now wonder if that's because he was using a different (up-to-date?) browser on a different computer, rather than because of waiting.

**Comment by spinecone** [comment] 2019-10-17 20:42
Since there have been multiple reports of this problem being resolved after switching from Edge to Chrome, has anyone experienced this problem on Chrome?

**Comment by robwhess** [comment] 2019-10-17 21:03
The one student who gave me more details about the problem said they experienced the problem on both Edge and IE and that everything worked fine when they switched to Chrome.  Sounds like an MS thing!

**Comment by spinecone** [comment] 2019-10-17 21:26
While we're working on resolving this, we recommend that folks running into this problem try again on Chrome and let us know if they're still seeing issues.

**Comment by d12** [comment] 2019-10-17 21:46
Hey all, this should be resolved now. We're going to dig into why this wasn't raised by our metric systems earlier, thanks for the patience!

**Closed by d12** 2019-10-17 21:46 UTC
