### ISSUE TITLE
Assignment Repository issues

### ISSUE THREAD

**Issue by alyxterrell** [education/classroom#1461] opened 2018-08-05 04:12 UTC
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to setup my assignment repository ..._

#### What happened (include screenshot if you can) ?
_the setup freezes at the same set of importing stater code ..._
![image](https://user-images.githubusercontent.com/42105241/43682453-f6a8e288-98b8-11e8-8e1b-a435a9146eb3.png)

#### Step-by-step reproduction instructions
I used the link sent by my professor, where it bean loading the first step, creating repository. Once finished, it began importing the starter code where it was frozen in the same place when I left it to run overnight. I tried redoing it by stopping and reclicking the link as well as restarting the computer, RStudio, my web browser, etc. I also deleted and recreated my account in case of any configuration issues from that end, but it is still freezing in the same place.
:raised_hands:

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by dawnngu18** [comment] 2018-08-05 11:40
I seem to have the same problem.

**Comment by BenEmdon** [comment] 2018-08-06 04:41
Hey @alyxterrell and @dawnngu18, thanks for reporting this. 

Looks like we have had a high load of people accepting repositories. We found an issue with our database load handling in #1458 and should have that sorted out on Monday. The fix should be #1459.

I'll follow up on Monday after we deploy the fix.

**Comment by BenEmdon** [comment] 2018-08-06 22:44
We deployed a fix earlier this morning. Please report back with and questions/concerns.
Thanks again for writing in.

Closing this for now.
Feel free to re-open this issue if you feel the problem is unresolved.

**Closed by BenEmdon** 2018-08-06 22:44 UTC
