### ISSUE TITLE
After accepting assignment, repo not fully created; restart failed

### ISSUE THREAD

**Issue by professordaehn** [education/classroom#1339] opened 2018-04-05 00:17 UTC
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_One of my students was trying to get started on an assignment. She accepted the assignment with the link I provided, the process kicked off but never completed. The name of the assignment appeared in her GitHub account list of repos, but when she tried to follow the link (so she could subsequently clone it), the link led to a 404 response._

#### What happened (include screenshot if you can) ?
_The assignment seemed to be in an inconsistent state. A link to the assignment was available in her account, but trying to visit the repo in the browser returned a 404. Likewise when I viewed the assignment from Classroom. I could see that she accepted the assignment, but when I tried to follow the link (from within Classroom), I was greeted with a 404 response._

_By the way: I "solved" her problem by create a local repo in which I set the remote repository to point to this address that kept returning the 404. I was able to push a file after doing this and the repo was suddenly available, i.e., viewable for interaction on a browser. However, none of the files that should have been there from the initial create action were there so we deleted the repo and she accepted the assignment again, this time without error._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

**Comment by Kadaaran** [comment] 2018-04-05 16:26
Hi @professordaehn , your issues is a duplicate of #1148 , I invite you to go there to be updated about it thank you for your patience !

**Closed by Kadaaran** 2018-04-05 16:26 UTC
Labels: duplicate
