### ISSUE TITLE
Importing starter code after new assignment hangs

### ISSUE THREAD

**Issue by weeser** [education/classroom#1842] opened 2019-05-29 14:16 UTC
**Describe the bug**
When accepting an assignment, the repository is created, but the import of starter code will randomly hang for some students.  This will hang for 5-10 minutes, sometimes a day or indefinitely.  Once it gets to anything longer than 5-10 minutes, this becomes unusable for running a coding lab.  This issue occurred 5/28/2019 between 11:30am and 1:30pm central.  The classroom is located [here](https://classroom.github.com/classrooms/50963792-kstate-cis300-su19). 

**To Reproduce**
1. Click on an assignment invitation link (PM for link).
2. Accept the assignment
3. The repository should be created and the starter code should begin to import.
4. The import of starter code may hang for undetermined amount of time beyond reasonable performance times for the size of the starter code. 

**Expected behavior**
The assignment repository is created and the code is imported under a few minutes.

**Additional context**
There are many other related issues to this issue, #1636 #1731 #1777 #1778 #1785 to name a few.  This class is ran as a studio, so students start and finish labs within the class period.  When getting the starter code randomly takes 10,20,30+ minutes to get, it prevents students from actually completing the assignments.  Sometimes deleting the repository and clicking the assignment again works, but this is not a guaranteed "fix".

**Comment by BenEmdon** [comment] 2019-05-29 14:32
Hey @weeser, thanks for reporting this in. 

Slow starter code imports are bottlenecked by the Source Import API's infrastructure. The Classroom team isn't responsible for this infrastructure. The team responsible for the Source Import API is making an ongoing effort to improve their infrastructure.

The slow down you mentioned coincides with a slowdown of imports across GitHub (site wide).

Unfortunately the source import API is not guaranteed to be instantaneous, so my advice to all teachers on GitHub classroom would be to get their students to accept assignments ahead of time.

If the situation doesn't improve, we will consider alternative approaches to starter code imports.

**Comment by BenEmdon** [comment] 2019-05-29 14:34
This is a duplicate of #1591 and we are tracking this issue there. Closing this issue in favour of #1591.

**Closed by BenEmdon** 2019-05-29 14:34 UTC
Labels: slow code import

**Comment by Alvarofdz97** [comment] 2019-05-30 12:58
Still having the same problem
