### ISSUE TITLE
student repo failed to inport (worked for other students) 

### ISSUE THREAD

**Issue by robustUTEP** [education/classroom#1712] opened 2018-12-01 07:18 UTC
**Describe the bug**
The student repo was not successfully created and "restart" doesn't work.

The error message from
   https://github.com/f18-arch1/project-3-video-toy-haomoy/import
is 
  "We found an error during import" with "There was an error pushing commits to GitHub."
When I click
   "restart"
Then I get a 404 from
    https://github.com/f18-arch1/project-3-video-toy-haomoy/import

**To Reproduce**

go to https://classroom.github.com/classrooms/42776572-f18-arch1/assignments/project-3-video-toy?students_page=3
click on "view repository" for user haomoy

**Expected behavior**
I expected to repo to exist and that I and the student could access it.

**Screenshots**
Let me know if anything else is needed.

**Additional context**
Please contact me and the student when this is resolved.

**Comment by BenEmdon** [comment] 2018-12-01 17:02
Hey @robustUTEP, this problem is related to the source import (which happens on GitHub.com). I will notify the appropriate teams.
In the meantime you should contact GitHub support for this issue: https://github.com/contact

**Comment by aleveren** [comment] 2019-01-31 18:22
I'm also having this problem.  Can someone please look into this?  I've already tried contacting GitHub support and was instructed to open an issue on this repository.

Here's the assignment where multiple users are unable to import the starter code:
https://classroom.github.com/classrooms/46382312-cse-100-winter-2019/group-assignments/project-2
The import step gets stuck indefinitely, and attempting to restart the import never seems to resolve it.

**Comment by BenEmdon** [comment] 2019-01-31 18:48
@aleveren its quite possible your issue is different from this one, so please open a new issue and include the assignment invitation link.

**Comment by Matiyeu** [comment] 2019-03-06 21:34
![image](https://user-images.githubusercontent.com/30661420/53915321-fb146780-405f-11e9-958f-09d4d7c0a522.png)
When I import from Giltab

**Comment by BenEmdon** [comment] 2019-03-06 22:43
@Matiyeu that issue is related to GitHub's source importer. Please [contact support](https://github.com/contact) since the problem pertains to GitHub.com (and not GitHub classroom).

**Comment by shaunakpp** [comment] 2019-08-20 17:24
Closing this as it is a duplicate of #1591 and https://github.com/education/classroom/issues/1591#issuecomment-523112964 describes the new and recommended option to import starter code.

**Closed by shaunakpp** 2019-08-20 17:24 UTC
Labels: slow code import

**Comment by jmckernan0** [comment] 2019-09-27 17:36
If on an enterprise system where students log into Google, ensure that student accounts have successfully synced. If not, sync account and the repository shou8ld complete loading.
