### ISSUE TITLE
Custom Labels Retained Through Assignment Invites

### ISSUE THREAD

**Issue by robmuh** [education/classroom#767] opened 2016-09-30 11:34 UTC
Just tested creating custom Labels (Signed, Suggestion, Reviewed, etc.) and deleting the "Won't Fix" and other confusing labels that are less relevant for an assignment repo and noticed they did not remain after the student accepted the invitation. Having these labels remain (as well as having any initially created issues also remain) is one of the most valuable additions to GitHub classroom that I can imagine. It is a very simple way to create a TODO sort of checklist for everything that needs to be done, and the "Signed" label I had wanted to use would ensure that students has seen, read, and signed certain things. I am happy to do anything I can to assist with this. After the semester has settled down I will attempt writing a command line tool to add these issues in bulk to all the repos in a given classroom (unless someone has already made that).

**Comment by nwoodthorpe** [comment] 2017-05-23 18:36
Duplicate of #846.

We certainly need better assignment repo initialization options. I'm not sure whether that means inheriting more from starter repos or having some sort of initialization interface, or perhaps another solution. I'll be looking into this when I have time!

**Closed by nwoodthorpe** 2017-05-23 18:36 UTC
