### ISSUE TITLE
Resource could not be found on github.com

### ISSUE THREAD

**Issue by winston** [education/classroom#254] opened 2015-09-23 06:15 UTC
Hi,

I created an assignment, invited myself to it but now I can't seem to access the assignment. 
![screen shot 2015-09-23 at 2 12 51 pm](https://cloud.githubusercontent.com/assets/2112/10038790/345be274-61fd-11e5-80b9-4ce93496cc63.png)

Clicking on the link gives me the error message "Resource could not be found on github.com".

----

Also, when a student accepts an assignment, it actually creates a repo under the org. 
How about considering creating the repo under the student's github account instead?

Thanks for the effort in this! Looking forward to seeing how this evolves! :bow:

**Comment by johndbritton** [comment] 2015-09-23 11:41
> Clicking on the link

Can you clarify what link you're clicking?

> Also, when a student accepts an assignment, it actually creates a repo under the org. How about considering creating the repo under the student's github account instead?

This is the intended behavior, and it's unlikely to change. The main reason is that we offer free private repositories to teachers for their courses and students for their own projects and we don't want school work to take away from the capacity offered on student plans. In addition, it's easier for the teacher to have everything in one place on GitHub, tracking down all of the individual user accounts is a bit difficult, especially for large courses.

**Comment by reedcwilson** [comment] 2015-09-23 22:50
@johndbritton I am having the same problem. I created a new issue (#265) but closed it because I didn't see this one.

I encounter this problem based on the following scenario:

I created an assignment `python-execution` and then sent a request (to myself) and accepted it. I then deleted the generated repository (`python-execution-reedcwilson`) in the organization. When I go back to Classroom and attempt to click on the assignment I get the error: "Resource could not be found on github.com."

![resource_not_found](https://cloud.githubusercontent.com/assets/1641775/10061102/28577fc2-6213-11e5-83a0-95a4b71019eb.png)

I realize that sending assignments to myself is not the intended use case; however, now I have two assignments that cannot be edited or even deleted.

The backing organization is: https://github.com/pg-programming

**Comment by robsonmarques** [comment] 2015-09-24 10:36
I am having this problem too. My scenario is the same of @reedcwilson. 

Plus, In cannot create new assignments (when I try I get the same error "Resource could not be found on github.com"). 

So I reseted my organization on Classroom, and now my Github organization does not appear in the list when creating a new organization on Classroom.

**Comment by johndbritton** [comment] 2015-09-24 10:50
> I then deleted the generated repository

This is what is causing the issue. Classroom for GitHub expects that you do not delete the repositories it creates.

@tarebyte We should handle this situation more gracefully, maybe we should create a `deleted` state for assignments or something like that where things still work in classroom but we tell the user that the repository on GitHub has been deleted and maybe provide a button to re-create it.

**Comment by winston** [comment] 2015-09-24 11:13
> Can you clarify what link you're clicking?

Sorry I wasn't clear. I meant the assignment link "Test 1".

> This is the intended behavior, and it's unlikely to change.

Thanks for the clarification on the intention. Appreciate it! :)

> This is what is causing the issue. Classroom for GitHub expects that you do not delete the repositories it creates.

I don't think this is the problem though. Although I have also deleted the generated repo, but the error occurred before the deletion.

One thing that I did similarly to @reedcwilson was to invite myself to the assignment, i.e. I am both the assignment creator and the student. Is that the problem?

Thank you!

**Comment by johndbritton** [comment] 2015-09-24 11:16
Thanks for the additional details @winston. I'm going to wait and see what @tarebyte thinks about this, but I think we're close to finding the root cause.

**Comment by johndbritton** [comment] 2015-09-24 14:27
I'm able to reproduce this, it's caused by a user deleting a repository or a failed deletion job.

@tarebyte we should also investigate where we're redirecting people when this error occurs. In one case I ended up on the new assignment page and in another I ended up on the assignments list.

**Comment by johndbritton** [comment] 2015-09-24 14:28
> and now my Github organization does not appear in the list when creating a new organization on Classroom.

@robsonmarques This is due to a failed deletion job. Since you deleted the repository manually before resetting your classroom the reset job failed (it couldn't find the repository to delete). We're working on a fix.

**Comment by robsonmarques** [comment] 2015-09-24 15:45
Thanks @johndbritton !

**Comment by johndbritton** [comment] 2015-09-24 17:37
@winston @reedcwilson @robsonmarques I've just deployed a fix for this. Can you try navigating to the assignment page on Classroom and see if you're still getting the error.

We haven't resolved the issues related to creating a new Classroom after a failed deletion yet, but let me know if the first step worked.

**Comment by winston** [comment] 2015-09-24 17:39
@johndbritton Yes. Works now. I can access the assignment page! Thank you! :)

**Comment by robsonmarques** [comment] 2015-09-24 17:58
@johndbritton I can't help on this, since I've reseted my organization. Sorry. Looking forward to create a new Classroom. :)

**Closed** 2015-09-24 18:23 UTC
Labels: bug

**Comment by johndbritton** [comment] 2015-09-24 18:24
This issue is resolved, but the related issue of not being able to add an organization to Classroom after a failed deletion still exists. Tracking that in https://github.com/education/classroom/issues/275.

**Comment by reedcwilson** [comment] 2015-09-24 18:41
@johndbritton is awesome!

**Comment by johndbritton** [comment] 2015-09-24 18:41
> @johndbritton is awesome!

Aww, shucks :blush:. Thanks @reedcwilson.
