### ISSUE TITLE
Classroom assignment page shows incorrectly

### ISSUE THREAD

**Issue by belgort-clark** [education/classroom#1819] opened 2019-05-03 18:02 UTC
**Describe the bug**
When a student clicks on an assignment URL they are brought to the page which shows extraneous HTML at the top

**To Reproduce**
1. Go to a classroom assignment page
2. See [this error](https://www.dropbox.com/s/imi1j4zlds3e886/Screenshot%202019-05-03%2011.00.10.png?dl=0)

**Expected behavior**
The additional buggy HTML should be removed

**Screenshots**

**Additional context**

**Comment by EricPickup** [comment] 2019-05-14 19:32
@BenEmdon this looks like a duplicate of #1830 which will be fixed in #1831.

**Comment by BenEmdon** [comment] 2019-05-15 00:22
Closing this duplicate, which we are now tracking in #1830

**Closed by BenEmdon** 2019-05-15 00:22 UTC
Labels: bug :beetle:, duplicate
