### ISSUE TITLE
Assignment from branch instead of repo

### ISSUE THREAD

**Issue by malloc82** [education/classroom#1338] opened 2018-04-03 18:49 UTC
### Feature request :sparkles:
Is it possible to have an option to create assignment from one branch of the original repository instead of copying the whole repository? Or an option to hide certain branch.

**Comment by Kadaaran** [comment] 2018-04-06 16:14
Hi @malloc82 , I believe your issue is a duplicate of #1270, I invite you to go there to be updated or to talk about it.

**Closed by Kadaaran** 2018-04-06 16:14 UTC
Labels: duplicate
