### ISSUE TITLE
No Organizations appearing

### ISSUE THREAD

**Issue by bnb** [education/classroom#239] opened 2015-09-22 16:34 UTC
I'm trying to set up Classroom, but it says no organizations are tied to my account. I created one as it suggested, and it still says there are no organizations. Am I doing something wrong?

**Comment by tarebyte** [comment] 2015-09-22 16:36
@bnb you may need to allow access to it. Checkout https://github.com/settings/applications and click on 'Classroom for GitHub'.

Make sure that you have enabled access for the organization.

**Comment by johndbritton** [comment] 2015-09-22 16:36
@tarebyte maybe we should add a `ProTip` to the organizations listings page pointing this out.

**Comment by tarebyte** [comment] 2015-09-22 16:37
@johndbritton agreed, will open a PR later

**Comment by justfortherec** [comment] 2015-09-22 17:18
Granting access at the above mentioned page does not resolve the issue for me. Classroom still says I don't have any organizations.

Logging out and in again does not help either.

**Comment by mcdickenson** [comment] 2015-09-22 18:23
+1 @justfortherec

**Comment by johndbritton** [comment] 2015-09-22 19:39
@justfortherec @mcdickenson can you provide the names of your organizations?

**Comment by mks-instructors** [comment] 2015-09-22 20:11
Same issue here. I have green checkmarks next to my orgs on the settings page for the "Classroom for GitHub" application. The app still shows no orgs.

**Comment by johndbritton** [comment] 2015-09-22 20:14
@mks-instructors What's the name of the organization you are expecting to see?

**Comment by mks-instructors** [comment] 2015-09-22 20:31
@johndbritton makersquare

**Comment by johndbritton** [comment] 2015-09-22 20:43
Thanks for the report, we're investigating this.

**Comment by johndbritton** [comment] 2015-09-22 21:11
@mcdickenson Can you provide a screenshot of the organization access section of this page from your GitHub account: https://github.com/settings/connections/applications/64a051cf1598b9f0658f

**Comment by johndbritton** [comment] 2015-09-22 21:26
@mks-instructors @justfortherec @bnb Has anyone else on your team added the organization to Classroom for GitHub. In some cases, folks aren't seeing their organizations in the list because they've already been added.

**Comment by hatboysam** [comment] 2015-09-22 21:40
I think the bug here has to do with the following steps:

  *  I granted classroom access to all of my orgs, but I am not admin of any
  * Classroom says 'hey, create an org!' so I do that
  * Classroom does not then re-prompt me for access to the new org, so therefore it still sees nothign

I had to go to https://github.com/settings/connections/applications/64a051cf1598b9f0658f to authorize classroom to access my new org, but I should not have,

**Comment by hatboysam** [comment] 2015-09-22 21:41
Actually I spoke too soon.  Even now classroom *still* does not see the org I created.  I even revoked access and granted it again, still nothing.

**Comment by BatuhanK** [comment] 2015-09-22 23:29
+1

**Comment by timofei7** [comment] 2015-09-23 00:44
+1   see 2 of my organizations but not the one i need.  i had created a classroom organization and then reset it and after that that particular org disappeared.

**Comment by tarebyte** [comment] 2015-09-23 02:14
Just to cover all of the bases, is anyone here using the new beta organizations on GitHub?

**Comment by justfortherec** [comment] 2015-09-23 06:32
@johndbritton 
> can you provide the names of your organizations?

https://github.com/VUAPTest
I have created it right after I had allowed classroom access to my organizations (when classroom suggested it).

> Has anyone else on your team added the organization to Classroom for GitHub. In some cases, folks aren't seeing their organizations in the list because they've already been added.

No, I'm currently testing alone.

> Can you provide a screenshot of the organization access section

![screenshot_2015-09-23_08-31-33](https://cloud.githubusercontent.com/assets/935534/10038951/9f168f7c-61cd-11e5-995a-c5f04806769b.png)


@tarebyte 
> Just to cover all of the bases, is anyone here using the new beta organizations on GitHub?

I don't use beta (at least not that I know of)

@hatboysam describes a slightly different issue. It still do *not* see the org even after granting access again.

**Comment by Danappelxx** [comment] 2015-09-23 15:04
:+1:

**Comment by johndbritton** [comment] 2015-09-23 16:05
@mks-instructors It looks like someone else in your organization already add it to Classroom for GitHub, they can invite you to gain access. I opened up another issue to track improvements related to your issue: https://github.com/education/classroom/issues/259

**Comment by johndbritton** [comment] 2015-09-23 16:07
@justfortherec I'm still stumped by your case. Can you check one more time for me by doing a hard refresh on the organizations dashboard (cmd+shift+r / ctrl+shift+r). It might be that your browser is caching that page incorrectly because I see that you should have access to your organization in the dropdown.

**Comment by BatuhanK** [comment] 2015-09-23 16:11
I have 2 organizations and one of them recently created but it's still not showing on https://classroom.github.com/organizations

**Comment by mcdickenson** [comment] 2015-09-23 16:21
@johndbritton It's working for me now. Thanks!

**Comment by johndbritton** [comment] 2015-09-23 16:25
@mcdickenson Can you elaborate on any steps that you took that might have resolved the issue?

**Comment by justfortherec** [comment] 2015-09-23 22:14
@johndbritton 
Apparently it is just me being stupid. Or it is your terminology being stupid. Probably a combination.

Classroom still tells me there is no organization and I have to add one before I can start. However if I click on the big green button, I'm led to a form where I can add a "new organization" by giving a title and selecting an organization from the dropdown menu which includes my already existing organization.

Are there two different kind of organizations? One GitHub-organization which I have to allow access to in order to be able to create a Classroom-organization?

I conclude that this is probably not a bug but a user issue (me) and a usability issue.

My apologies for not looking careful enough.

**Comment by johndbritton** [comment] 2015-09-24 10:41
@justfortherec thanks for checking, yeah that's our fault for not being more clear. We're going to fix that up in #252.

I'm glad to hear that it's working for you though.

Is anyone else still having an issue? If you don't have any organizations click the green button and check the drop down menu. L

**Comment by johndbritton** [comment] 2015-09-24 10:59
@bnb You need to [grant access](https://github.com/settings/connections/applications/64a051cf1598b9f0658f) to an organization that you're an admin of.

**Comment by johndbritton** [comment] 2015-09-24 11:03
I've looked through every report on here and I don't think there's actually a bug in the code, but clearly there's a UX issue here. Closing this in favor of #252.

If you don't see the organization you're looking for in Classroom for GitHub, please make sure you:

1. Are an admin of the organization you're trying to add
2. Have [granted access](https://github.com/settings/connections/applications/64a051cf1598b9f0658f) to the Classroom for GitHub organization
3. Have [added](https://classroom.github.com/organizations/new) the organization to Classroom for GitHub.

**Closed by johndbritton** 2015-09-24 11:03 UTC
Labels: bug

**Comment by nicolethenerd** [comment] 2017-10-31 18:54
Why is this closed? If you are not an admin of your organization but your organization has already been added, you will still see no organizations on the "Select an organization for your new classroom" and be prompted to "grant us access". When you click "grant us access", you will see that your organization has already been added, and it's not at all clear what to do next.
