### ISSUE TITLE
Students import of starter project failed

### ISSUE THREAD

**Issue by FranckSilvestre** [education/classroom#1796] opened 2019-03-12 15:56 UTC
The import of the starter project failed for all of my students today (about 35) but 1.
The progress bar stalled during more than one hour. 
The starter code has no large files.

Last week, on another assignment, students were stuck about 50 minutes before the import finished.

**Comment by andreafioraldi** [comment] 2019-04-10 09:55
![Screenshot at 2019-04-10 11-50-27](https://user-images.githubusercontent.com/16168186/55869713-58cc3000-5b87-11e9-8bf9-cc0b3739f0c7.png)

Same problem here for the Advanced Operating System and Virtualization class at Sapienza Rome

/cc @alessandropellegrini

**Comment by alessandropellegrini** [comment] 2019-04-10 09:59
I can add to this that even if the status bar doesn't complete, the repo is correctly cloned. Maybe it's a problem related to the acknowledgement to the frontend.

@andreafioraldi I can see your cloned repo in the organization. Could you please confirm if you have access?

**Comment by andreafioraldi** [comment] 2019-04-10 11:17
Yeah I have the repo.
It hanged again also after a refresh but it created the repo this time.

**Comment by nasseef** [comment] 2019-05-21 15:50
> Yeah I have the repo.
> It hanged again also after a refresh but it created the repo this time.

Same issue starting Sunday 5/19/19.

**Comment by oliviercailloux** [comment] 2019-05-26 17:59
I see this behavior systematically since about a month when my 25 students all try to create an assignment repository at (about) the same time at the start of the session: about half of them get apparently stuck at the screen shown above. In fact, the repository is created, but some students do not get it and wait there for minutes before realizing that the repostory in fact exists. Even when they observe that it exists, some are worried that something goes wrong with their repository. 

As I use GitHub Classroom for graded exercices, I need to be able to trust the environment (and my students need to trust it as well)!

**Comment by oliviercailloux** [comment] 2019-05-26 18:00
This issue duplicates #1795

**Comment by shaunakpp** [comment] 2019-06-26 23:05
This is a duplicate of #1591 and we are tracking this issue there. Closing this issue in favour of #1591.

**Closed by shaunakpp** 2019-06-26 23:05 UTC
Labels: slow code import
