### ISSUE TITLE
Repository setup hanging / being slow.

### ISSUE THREAD

**Issue by rkomorn** [education/classroom#1460] opened 2018-08-04 21:56 UTC
#### What you were trying to do ?
Several of our students are currently experiencing difficulties getting their repo set up for this weekend's assignment.

#### What happened (include screenshot if you can) ?
The error they're seeing is:

![image](https://user-images.githubusercontent.com/523308/43680741-a5db26fe-97f5-11e8-9ec6-287fa3e74d79.png)

The repo itself takes a while to be created. Once it is created, you'll see something like this:

![image](https://user-images.githubusercontent.com/523308/43680749-136ec838-97f6-11e8-8f03-a2260a1710bf.png)

So far, some repos have been stuck this way for at least an hour.

I'm not sure when the issue started but I can tell that several other students were able to create repos successfully. My best guess is that the last successful one happened around 12pm PDT on 8/4 .

#### Step-by-step reproduction instructions
Reproduce by trying to accept this assignment:  https://classroom.github.com/a/mZxrw9sW

**Comment by BenEmdon** [comment] 2018-08-06 04:48
Hey @rkomorn, thanks for reporting this. 

Looks like we have had a high load of people accepting repositories. We found an issue with our database load handling in #1458 and should have that sorted out on Monday. The fix should be #1459.

The slowness on GitHub.com is not the classroom project but I will alert the team responsible about slow times.
> ![](https://user-images.githubusercontent.com/523308/43680749-136ec838-97f6-11e8-8f03-a2260a1710bf.png)

The assignments your students accepted should eventually process and be created. If you need any support with that feel free to follow up with any questions you might have.

I'll follow up on Monday after we deploy the fix.

**Comment by rkomorn** [comment] 2018-08-06 16:42
Yeah it did seem like things started working at some point. It was definitely disruptive.

**Comment by BenEmdon** [comment] 2018-08-06 22:05
We deployed a fix earlier this morning. Please report back with and questions/concerns. 
Thanks again for writing in.

Closing this for now. 
Feel free to re-open this issue if you feel the problem is unresolved.

**Closed by BenEmdon** 2018-08-06 22:06 UTC

**Comment by BenEmdon** [comment] 2018-08-24 15:34
@ramkumargopal would you mind [opening a new issue](https://github.com/education/classroom/issues/new?template=bug_report.md) and providing details? This issue was fixed so while your issue might be similar, it is technically different.
