### ISSUE TITLE
Student identifier request

### ISSUE THREAD

**Issue by franktank** [education/classroom#481] opened 2016-03-07 13:46 UTC
Feature request

Implement authentication system that allows for both user sign up with optional fields for information requested by teacher and GitHub OAuth.

**Comment by tarebyte** [comment] 2016-03-07 14:00
@franktank thanks for the feature request.

I think what you're looking for is that when a student signs with GitHub Oauth, they can then add more metadata to their profile at the request of the teacher. Is this correct?

Students have to sign up with the GitHub Oauth flow otherwise we don't have a way to add them to the GitHub organization.

**Comment by franktank** [comment] 2016-03-07 14:17
Yeah, but I'm not quite sure what the best way of implementing that would be.

**Comment by johndbritton** [comment] 2016-03-08 15:30
Closing as a duplicate of https://github.com/education/classroom/issues/448

**Closed by johndbritton** 2016-03-08 15:30 UTC
Labels: feature-request
