### ISSUE TITLE
Restrict access to roster-students only 

### ISSUE THREAD

**Issue by cboettig** [education/classroom#1140] opened 2017-09-06 23:32 UTC
It appears that any GitHub user who knows the  "assignment link" can create an assignment repo in the course organization, even if those repos are private & the template repo is private, etc.  Anyone with access to this link is also made a 'member' of the Organization, and granted the default rights of any other member, including viewing the user names of all other (private) members, contents of private repositories, etc (which raises potential student privacy issues).  

I realize instructors will usually have a private channel to students through which they can distribute this link, but nonetheless emailing around a single link to 100s of students that has essentially password-like properties feels like I am not modeling good security hygiene to my students at very least. 

It would be nice to have the option to restrict this privilege to, say, students explicitly listed in the roster.  The interface asks students to identify themselves on the roster, but currently gives the students the ability to "skip this step" as well, and just go ahead and create the private repository.  This creates a bit more friction for deploying in large classes, but the new roster interface is very slick and I hope would facilitate providing a bit finer-grained access, where only accounts already associated with emails would be granted privileges (more closely matching how permissions are granted across the rest of GitHub)

**Comment by cboettig** [comment] 2017-09-07 03:36
Follow-up note: I believe this issue only affects group assignments, which involve creating teams and thus making any individual with the link into a member of the team and the organization as a whole.  This contrasts from the behavior of the "individual assignment" links, where the individual remains an "outside collaborator".  It would still probably not be appropriate to list even these individual assignment links in a public place (say, a public-facing course website), but at least doesn't pose the unexpected privacy risks of the group assignments.

I do think the way any user automatically gains membership to the organization and associated privileges if they have a group assignment link is an issue that should be addressed (ideally in both cases the instructor should be able to restrict who can accept to the roster, e.g. eliminate the "skip this step" option).  Meanwhile it would at least be good to better document this behavior so it doesn't catch some instructor unaware.

**Comment by mozzadrella** [comment] 2017-09-24 17:57
Hi @cboettig. We've kept the invitation process pretty lightweight so far, and introduced rosters to help teachers keep better track of student's GitHub identities. 

I'm putting your feature request on the roadmap as awaiting triage, and we'll tackle it in the next sprint, either in documentation or in the product. Thank you for opening.

**Comment by bulletshot60** [comment] 2019-01-08 18:02
Just an idea, @mozzadrella, if adding a student to the roster sent them an invite to the organization, would it then be possible to limit accepting assignments to only organization members?

**Comment by Sadikum** [comment] 2019-04-11 13:29
Hi, is there any update on this issue ? I'm very interested in this feature too. Either as @bulletshot60 or another way I'm seeing would be to enter the list of Github's ID in the roster and limit to only those people.

**Comment by JarrettBillingsley** [comment] 2019-05-27 19:27
Yeah, this feels like a weird honor system to me. What would be great is if **an individualized link were created for each student.** Even if GH doesn't send emails out itself, if I could get a CSV of links/user IDs (I use their university emails as IDs) I could send the emails out myself.

**Comment by d12** [comment] 2019-08-06 18:14
As another note here, there's opportunity to improve the entropy of the invitation links to lower the possibility of students joining a wrong assignment through typo or via malicious means.

Our keys are b64, 6 chars, which means 68 billion combinations. Upping this to 8 chars would mean 281,474 billion combinations which I feel is sufficiently large.

There's room for investigation here into how we can address the concerns listed by everyone in this issue. Adding to our backlog for one of our engineers to look into. Thanks everyone for your input!

**Comment by bulletshot60** [comment] 2019-08-06 18:19
Just to comment again on what we've wound up doing at my University.  We use Canvas which is accessible only by University students.  We put the assignment link in the Canvas assignment description (or as an external tool).  This way the URL is not available until we're ready for it to be, and it is only accessible to University students enrolled in the course.

(Due to the keys being b64, I'm not concerned about students or others guessing the URL.  I am concerned about students not in the class being able to access the assignment via the URL with no hindrance whatsoever.)

**Comment by JarrettBillingsley** [comment] 2019-08-06 18:20
I know you probably can't say when it'll be done, but is there a chance this might be ready in time for the fall semester (by the end of August)?

**Comment by d12** [comment] 2019-08-06 18:25
Thanks for the update @bulletshot60 :)

@jarrettBillingsley There is still some investigation needed to be done. Rosters are very lightweight and self-serve at the moment, we'd need to add a decent bit of functionality to have "verified" students, whether that be via email address on their GitHub profile or via one-time-use personalized invitation URLs. 

Let me get some thoughts from our engineering team and we'll get back to you on this.

**Comment by d12** [comment] 2019-09-18 19:59
:wave:!

I'm closing this one out as a duplicate of https://github.com/education/classroom/issues/1140. This is something we want to tackle at some point, we'll post something in the other issue when we begin work.

**Closed by d12** 2019-09-18 19:59 UTC
Labels: Hacktoberfest, feature request, student roster :man_student: :woman_student:

**Comment by JarrettBillingsley** [comment] 2019-09-18 20:01
A duplicate of itself...?

**Comment by d12** [comment] 2019-09-18 20:20
@JarrettBillingsley Whoops, wrong link. https://github.com/education/classroom/issues/377
