### ISSUE TITLE
Student repository creation stuck

### ISSUE THREAD

**Issue by mstine** [education/classroom#1758] opened 2019-02-04 16:19 UTC
**Describe the bug**
Student @mml2 tried to create a repo for assignment https://classroom.github.com/classrooms/42622010-ddd-event-driven-microservices-course/assignments/2019-02-oreilly-sacon about 15 minutes ago. It is still stuck. No movement has happened on any of the progress bars. I confirmed from my dashboard there is not a repo for @mml2.

**To Reproduce**
1. Visit and click on invitation link: https://classroom.github.com/a/68TqzACk
2. Watch and wait. :-)

**Expected behavior**
The repo is successfully created, as all of the other students' were.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rjsvcs** [comment] 2019-02-09 17:55
This is a duplicate of a bug that I reported at almost exactly the same time as you (issue #1757). Glad it's not just me.

**Comment by BenEmdon** [comment] 2019-02-22 02:57
@mstine Did this only happen for the one student (`mml2`)? Or did this happen to all of your students?

**Comment by mosser** [comment] 2019-03-12 19:29
I am also stuck for 2 groups created today in my class. This is really annoying. I did the import "by hand" (cloning the empty repo and pushing the starter code) so that my student can work.

**Comment by sangkilc** [comment] 2019-03-13 19:41
Same problem here. Had to manually copy the starter code for few students in my class.

**Comment by shaunakpp** [comment] 2019-06-26 23:10
This is a duplicate of #1591 and we are tracking this issue there. Closing this issue in favour of #1591. I've also added a "slow code import" tag so that we can reference this issue.

**Closed by shaunakpp** 2019-06-26 23:10 UTC
Labels: repository setup :package:, slow code import
