### ISSUE TITLE
Help wanted: Disable clone-notification email.

### ISSUE THREAD

**Issue by kaspersoerensen** [education/classroom#1268] opened 2018-02-08 17:01 UTC
Hi there,

Whenever a student accepts an invitation to an assignment I get a Notification on Email regarding that. It is possible to disable that?

The screendump below shows my current notification settings.
![skaermbillede 2018-02-08 kl 18 00 08](https://user-images.githubusercontent.com/2018894/35986674-fdc3baac-0cf9-11e8-816b-2bbeca46ff66.png)

**Comment by tarebyte** [comment] 2018-02-08 19:15
Duplicate of https://github.com/education/classroom/issues/1230

Unfortunately we can't turn off emails for the notification at this time, sorry about that @kaspersoerensen

**Closed by tarebyte** 2018-02-08 19:15 UTC
