### ISSUE TITLE
Students import failing

### ISSUE THREAD

**Issue by mikiehan** [education/classroom#1690] opened 2018-11-04 03:08 UTC
**Describe the bug**
Import fails for one of my students with Github ID dannia3. There are other students who have successfully imported.

Problem repo: https://github.com/cbu-egr222-fa18/hw6-dannia3/  
assignment: https://classroom.github.com/classrooms/42749779-cbu-egr222-fa18/assignments/hw6
Invitation link: https://classroom.github.com/a/sRXFR1nF

When he clicks on the invitation link, it creates the repository fine but importing the starter code fails. He has tried restarting his computer, refreshing the website, signing out of github, etc but all unsuccessful. 

**To Reproduce**
N/A

**Expected behavior**
Import success

**Screenshots**
![image](https://user-images.githubusercontent.com/13935460/47959546-184b0380-dfa4-11e8-946e-9a98e6b19810.png)

**Additional context**
N/A

**Comment by mikiehan** [comment] 2018-11-04 03:12
I also see import failure for another student with GithubID isaOrdaz

![image](https://user-images.githubusercontent.com/13935460/47959562-a6bf8500-dfa4-11e8-942b-e5917923866d.png)

**Comment by BenEmdon** [comment] 2018-11-04 15:50
Hey @mikiehan, thanks for reporting this.
This issues is happening on GitHub.com so please contact support at https://github.com/contact to get support on this as fast as possible.
I will be sure to relay this issue to the appropriate team too.

**Comment by mikiehan** [comment] 2018-11-08 16:19
I didn’t hear anything from them ☹

**Comment by BenEmdon** [comment] 2018-11-08 16:43
This might be related to to #1691. I'll cross reference to confirm. 

I'll also go ahead and reset those assignment repos for you.

**Comment by BenEmdon** [comment] 2018-11-08 16:57
It appears that the problem was caused by a GitHub.com outage on Friday the 2nd of November 
https://status.github.com/messages/2018-11-2. This was related to https://github.com/education/classroom/issues/1691.

I reset the assignment repos for the following users:
- dannia3
- isaOrdaz

Tell these students to redeem a new assignment repo at https://classroom.github.com/a/sRXFR1nF

Closing this issue for now since it should be resolved. Please reopen this issue if any other students were effected by this incident.
@mikiehan apologies for the support delay.

**Closed by BenEmdon** 2018-11-08 16:57 UTC
