### ISSUE TITLE
Cannot accept an assignment

### ISSUE THREAD

**Issue by FanBu** [education/classroom#1278] opened 2018-02-16 18:09 UTC
Cannot accept an assignment. Reported by many different users with same assignment.
It seems like some lock is not released and fork cannot be done properly.
Please resolve this bug quickly since the due of this assignment is coming.

**Comment by Kadaaran** [comment] 2018-02-16 18:16
Hi @FanBu  !

We are aware of this issue and are trying to fix it.
Unfortunately your issue is a duplicate of #1271
I'm going to close this one and invite you to go to #1271 to get more informations and to be updated regarding this issue.

Thank you for reporting this issue.

**Closed by Kadaaran** 2018-02-16 18:16 UTC
