### ISSUE TITLE
Class Invite/Repository Creation Taking Excessive Time

### ISSUE THREAD

**Issue by rjsvcs** [education/classroom#1757] opened 2019-02-04 16:10 UTC
**Describe the bug**
Many students are reporting that it takes an excessively long time to import starter code after accepting an assignment. When students click the classroom invitation link and accept the assignment, the progress bar for creating the repository moves quickly, but then the progress bar for importing starter code hangs, usually around 80-80%. Sometimes for hours. If the student returns to the classroom, they see the page stuck at the same point.

In most cases, the repository exists and the starter code has been imported. I can send the student a link to their repository and they are able to use it. But this is an annoying and manual process that is not scalable.

**To Reproduce**
1. Click on invitation link.
2. Click on button to accept classroom invite.
3. Progress bar for creating repository (left side) moves quickly.
4. Progress bar for importing source code freezes at 80-90%. Sometimes for hours. Even days.

**Expected behavior**
I expect the repository to be created and the starter code imported within a minute or two. I expect the students that return to the classroom later to find the link to their repository.

**Screenshots**
.
![image](https://user-images.githubusercontent.com/22302214/52220525-10ce1b80-286d-11e9-8e5b-73125a16a4a1.png)

**Additional context**
NA

**Comment by eblanton** [comment] 2019-02-14 18:12
I am also experiencing this, and students are additionally having trouble accessing some repositories that appear to have been created successfully using git command line over https.  One student also could not download a .zip of his repository, despite it showing files on the web page (the clone/download menu button would not open a dropdown at all).

I have 198 students, and this is becoming a large problem.

**Comment by BenEmdon** [comment] 2019-02-21 20:28
@rjsvcs I went ahead and investigated your repository and I found that it had an invalid web hook (related to #1647). I went ahead and manually fixed webhooks on your classroom _CSCI-124-03_. Your students should see their assignments import. 

I went ahead and tried it out on your classroom and can confirm it is working as expected. I will go ahead and close this issue for now. @rjsvcs please reopen this issue if you experience it again.
---
@eblanton could you give me a link to an assignment in your classroom so I can investigate your classroom? Please do so in a new issue and tag me.

**Comment by rjsvcs** [comment] 2019-02-26 19:45
@eblanton Thanks for this. I have had one student run into the problem since you fixed it (I'm assuming it was a fluke because many dozens of other students have not had a problem). However, several of my colleagues are seeing the issue. Is there a way that we can fix the webhook issue without submitting a bug report?

**Comment by BenEmdon** [comment] 2019-02-26 23:25
This issue is actually an ongoing (unreported) outage on GitHub.com. Please see #1778 for details.

**Comment by BenEmdon** [comment] 2019-02-28 14:25
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Closed by BenEmdon** 2019-02-28 14:25 UTC

**Comment by xieyuxi1107** [comment] 2019-09-11 13:20
I have the same problem, just that my code is not actually imported into the repository. Why is that?
