### ISSUE TITLE
Add option to copy the wiki from the starter code repo

### ISSUE THREAD

**Issue by jayvdb** [education/classroom#749] opened 2016-09-23 03:17 UTC
Like #546 , for copying the wiki.

My assignments are copies of existing OSS projects, so the assignment text cant be on the `master` branch.

Using an extra branch is not user friendly, as it can't be the default branch (#673) , which means the students need to find the branch - the GitHub interface for non-default branch is not intuitive.

Using issues from the starter repo will be an improvement, but is not ideal for providing large amounts of information, translations for multiple languages, hints and tips, etc.

**Comment by CGA1123** [comment] 2016-09-24 11:33
I don't think creating independent copies of wikis is the best way forward for sharing large portions of information for assignments.

The larger the amount of info, the more likely it'll need some changes, or will have some mistakes in it. 

Creating independent copies of wikis, will make it a pain to propagate changes to the wiki through to all students, would it not?

**Comment by nwoodthorpe** [comment] 2017-05-23 18:53
I'm going to close this as a duplicate of #846. I'm not 100% sure we want to do this, but it certainly falls under the umbrella of "Repo initialization is hard right now".

**Closed by nwoodthorpe** 2017-05-23 18:53 UTC
