### ISSUE TITLE
Internal Server Error when accessing Assignment

### ISSUE THREAD

**Issue by JayPeeTeeDee** [education/classroom#2227] opened 2019-08-12 17:44 UTC
**Describe the bug**
Internal server error page displayed when trying to access [Assignment Link](https://classroom.github.com/classrooms/2061356-software-product-engineering-for-digital-markets-2019/group-assignments/a3-mobile-cloud)

**Additional context**
1. [Classroom Page](https://classroom.github.com/classrooms/2061356-software-product-engineering-for-digital-markets-2019) also shows internal server error
2. Other assignment in classroom is still accessible from direct link
3. I was trying to create an assignment with the same name shortly after deleting the previous assignment after testing out with team creation and deletion

**Comment by EricPickup** [comment] 2019-08-12 17:58
Hi @JayPeeTeeDee,

I've taken a look and somehow your `grouping` (set of teams) on one of your group assignments is null. Not sure how this happened but I can update it for you. Is it alright if I update your set of teams on your group assignment to be the same as the other one?

**Comment by JayPeeTeeDee** [comment] 2019-08-12 18:09
The teams for both A3 and A4 should be empty as I have not created any teams under both assignments.

> Is it alright if I update your set of teams on your group assignment (A4) to be the same as the other one (A3)?
No issues with this, thank you

**Comment by EricPickup** [comment] 2019-08-12 18:24
@JayPeeTeeDee the actual GitHub teams can be empty, but when you create a group assignment you have to choose or create a new set of teams. Not sure how yours became nil but I'll look into it if this comes up again:
![image](https://user-images.githubusercontent.com/1490434/62887887-0b0d3300-bcf3-11e9-8351-790b971b6506.png)

I've updated your grouping for that assignment and it looks like everything is working now!

**Comment by JayPeeTeeDee** [comment] 2019-08-12 18:30
Yes it was fixed, but I've managed to reproduce the internal server error again.

These were my exact steps:
Step 1: Delete A3 Assignment
Step 2: Create new assignment (with the same name)
- Under `Create a new set of teams`: Entered `A3 Teams`

**Comment by EricPickup** [comment] 2019-08-12 19:25
@JayPeeTeeDee it looks like your classroom already has a team set called "A3 Teams". I tried reproducing it and found that when creating a new set of teams with the name `A3 Teams` caused the error to occur the second time because that set of teams already existed. The error handling for that is broken and I'll create a bug report for this.

For now your classroom is fixed (A3 is using the same grouping as A4 at the moment). If you'd like to change it to A3 teams make sure you select it from the existing set of teams instead of trying to create `A3 teams`.

**Comment by d12** [comment] 2019-08-13 01:51
Closing as this is being tracked in https://github.com/education/classroom/issues/2230. Thanks for the report!

**Closed by d12** 2019-08-13 01:51 UTC

**Comment by JayPeeTeeDee** [comment] 2019-08-13 02:56
Thank you for the help!
