### ISSUE TITLE
Can not add specific user as a collaborator to assignment.

### ISSUE THREAD

**Issue by djibouti33** [education/classroom#1575] opened 2018-09-18 05:20 UTC
#### What you were trying to do ?
We're using GitHub classroom to facilitate coding challenges for prospective candidates. We tested internally and everything worked. I sent the assignment link to a few candidates and that seems to have worked well too.

#### What happened (include screenshot if you can) ?
We sent to one candidate today and they were not able to load the project. Received error "We were not able to add you to the assignment as a collaborator, please try again."

Here's a [screenshot](https://gm1.ggpht.com/V2axv843SlGq0QtjFR81Rq4iu20uQsDwt7hveBFPKqYUSXDrwBqyVdgQuM3Zs162GJSQWfnbBA9luakEQ4WVU45JjNo3TULqfLnm9JXDseg9Ha8qEA67ABUTOM4bQ3QZEmiMahK74WM3z0NKU2ebckRGGrUd-IrfHz96vxegTpYzOfUJRCFyoEIpVaWttLXghgRBRkBBkprnPvSA1Qg9Cz1ZjwsdC13IUKXo0_BTZ3YGQ_ovrmoM33gJaMIM1U8Uwc9wTwryhMsGFLt5urU4bKFMgm5kpKHB5M3W7Oc2TGjlltUV-0Nc3yMdvtmaGJHQqA-nUKlGLKl_z9w969FGwtObtnnlvsuovVO9JFFA6taEgbzb2-EglwWiNLzjFIYzB21RXLOrBzGf0N6XP9iVyQ9LqbApfVaNqh85OLzLiFxoMBzrbEVd8LUC_V8IXbAWYBDXuQ3b-EzOL1-stWniFfSsPSIfBn_euK7KhDTAinv5sSqe9h-yJ_NB0UXcJJlycYeLPoslbHTQrdRa1qjmR5fjm0XFnJdI4EsAYu43_cQSdBXq5yDDHFpSPKzzoMrG_1jFLCutCIaXyBzHG3decZWxFjxTf9qbWJcWEMhzRxq6o5nK5WzKkaPFiMle8gIiigaSJ-N0vTwWE_yV1oNKXiAq3wDlePQjRzjIKvX93iUNeipLP-tG4HWvSLDroBX4onInFjPrrQBEknh1=s0-l75-ft-l75-ft).

#### Step-by-step reproduction instructions
* Sent assignment URL to candidate (https://classroom.github.com/a/Gc5yFdMc)
* Candidate clicked on URL, authenticated, but project failed to import.
  * I'd like to avoid posting the user's account who we're trying to add

**Comment by johndbritton** [comment] 2018-09-18 13:56
> Here's a screenshot.

I can't access your screenshot.

**Comment by johndbritton** [comment] 2018-09-18 13:59
> I'd like to avoid posting the user's account who we're trying to add

Can you please email `education@github.com` and reference this issue to specify the user that is having problems privately.

**Comment by djibouti33** [comment] 2018-09-19 17:37
Thanks @johndbritton! I sent an email yesterday and also included the screenshot.

**Comment by johndbritton** [comment] 2018-09-19 21:30
@djibouti33 I'm not ignoring this issue, but I need to wait for https://github.com/education/classroom/pull/1574 to be deployed before I can investigate the details of what are causing this further.

> I sent an email yesterday and also included the screenshot.

I have not been able to find this email that you sent. Did you send it to `education@github.com`, reference this issue, and mention me by name?

**Comment by BenEmdon** [comment] 2018-10-19 18:54
Hey @djibouti33, which specific user wasn't able to be accepted as a collaborator? Would you mind providing me with their GitHub handle?

You can of course conceal their identity by emailing their handle to `education@github.com` and please CC `benemdon@github.com`

**Comment by mozzadrella** [comment] 2018-10-25 18:32
@djibouti33 we received your email, and @BenEmdon is on the case to investigate.

**Comment by BenEmdon** [comment] 2018-10-29 20:49
Hey @djibouti33, how many seats do you have left in your organization plan?

**Comment by BenEmdon** [comment] 2018-10-29 21:16
Hey @djibouti33 
I found that the following error when the users you specified tried to accept their assignment invitations:
> The UpActive organization requires all members to have two-factor authentication enabled. // See: https://developer.github.com/v3/orgs/members/#edit-your-organization-membership

It looks like neither of the users that you specified have two factor auth on their account and therefore aren't able to be added to your org as outside collaborators.

To resolve this problem:
* Tell the users that you had invited that they are required to have two factor auth set up on their account (see https://help.github.com/articles/configuring-two-factor-authentication/)
* Or drop the constraint about two factor auth (Not preferable)

I'm going to close this for now and open a separate issue about presenting more detailed errors to users!

**Closed by BenEmdon** 2018-10-29 21:16 UTC
Labels: bug :beetle:

**Comment by jbschrades** [comment] 2019-05-28 19:46
We're having the same problem.  I've tried it with the Organization 2FA turned off and on.  Student 2FA turned off and on.  That doesn't seem to be the cause.

**Comment by BenEmdon** [comment] 2019-05-28 20:02
@jbschrades Would you mind providing an assignment link and screenshot of the error? 
Also can you confirm that you are on the GitHub education organization plan? You can check this by going to the `settings/billing` tab on your GitHub Organization.
