### ISSUE TITLE
Classroom is saying I don't have any organizations yet, but I do

### ISSUE THREAD

**Issue by hatboysam** [education/classroom#244] opened 2015-09-22 20:14 UTC
I created an org with the flow but Classroom can't see it.

**Comment by sebie** [comment] 2015-09-22 20:17
Duplicate of #239 ?

**Comment by johndbritton** [comment] 2015-09-22 21:18
Closing this as duplicate of #239. Please make sure you have authorized the application to access an organization that you have administrative privileges on, once you're sure of that, please provide additional details in #239.

**Closed by johndbritton** 2015-09-22 21:18 UTC
