### ISSUE TITLE
Next page button doesn't work on group assignments

### ISSUE THREAD

**Issue by sfikas** [education/classroom#1316] opened 2018-03-21 08:34 UTC
The 'next page' button takes me back to the same page.
The list is a set of group assignments:
https://classroom.github.com/classrooms/23520047/group-assignments/psee-heim-2017-2i-seira-askiseon

**Comment by Kadaaran** [comment] 2018-03-21 17:18
Hi @sfikas thank you for reporting this issue.
Yours is a duplicate of #1303 I invite you to go there for more informations thank you 🙏

**Closed by Kadaaran** 2018-03-21 17:18 UTC
Labels: duplicate
