### ISSUE TITLE
Failed import due to freeze resulting in bare repository

### ISSUE THREAD

**Issue by joenash** [education/classroom#784] opened 2016-11-15 18:47 UTC
>  There is a bug on github classroom where maybe 1 time out of 100, clicking the link will create a repository then freeze while importing files, leaving a bare repository; the only remedy is for me to delete the repo, and then have the student click the link again.  For now, it's probably easier for me to do this than for it to be debugged (sounds like a race condition) so am just mentioning FYI.

From a user with approx 250 students, making weekly assignments.

**Comment by joenash** [comment] 2016-11-15 18:47
cc @tarebyte

**Comment by jayvdb** [comment] 2016-11-15 20:11
I encountered something very similar to this last week, and it has only happened once.  To work around the problem, we pushed the "starter code" repo into the student assignment repo.

**Comment by dhowe** [comment] 2016-11-16 03:55
Same here -- very frustrating, as the students think they've done something wrong, and try all sorts of random solutions, when actually it is a github bug. For us it seems to happen maybe 3-5% of the time or more; then the teacher has to manually push the starter code into the students repo -- a huge hassle in a class of 200.

**Comment by alexanderbazo** [comment] 2016-11-24 14:53
Same here. The problem does not seem to be reproducible but has occurred for ~10 out of 60 students. 

Not sure about the following:
It seems to happen more frequently when a lot of students tried to import the source repository simultaneously during class. There were fewer problems reported when the students imported a similar test assignment at home (and not simultaneously).

**Comment by meneguzzi** [comment] 2016-12-06 16:55
Same thing with me throughout the semester, however, this seems to have been a lot more frequent than 1 in 6. Some students seemed to have been unluckier than others. I tried deleting the repos and asking the students to try again, only to see the same thing happen over and over.

**Comment by nwoodthorpe** [comment] 2017-05-23 17:24
Duplicate of #772.

Thanks for the reports everyone. I'll try to get time this week to dig into this.

**Closed by nwoodthorpe** 2017-05-23 17:24 UTC

**Comment by belgort-clark** [comment] 2019-02-22 22:21
I'm today seeing this error with an assignment.
