### ISSUE TITLE
Can move farther than first page in an assignment

### ISSUE THREAD

**Issue by bvelez** [education/classroom#1325] opened 2018-03-25 15:38 UTC
Classroom: UPRM-CIIC4010-S18 Advanced Programming
Assignment: MineSweeper

I cannot go beyond the first page of assignemnt:
https://classroom.github.com/classrooms/36892910-uprm-ciic4010-s18-advanced-programming/group-assignments/minesweeper

-Bienve

**Comment by Kadaaran** [comment] 2018-03-26 09:43
Hi @bvelez , your issues is a duplicate of #1303  
I invite you to go there to be updated about it. Thank you !

**Closed by Kadaaran** 2018-03-26 09:43 UTC
